conda-recipe/meta.yaml
`llvmdev` is necessary in `numba-dppy`.
Previously IntelPython/Numba required it.
Also `llvm-spirv` is not used in build.
=> Add llvmdev in conda-recipe

numba_dppy/__init__.py, numba_dppy/config.py, numba_dppy/dppl_offload_dispatcher.py, numba_dppy/tests/__init__.py
dppl_config.py contains flag `dppl_present` which indicate that `dpCtl`
and devices are available.
As `numba-dppy` will depend on `dpCtl` then the check is not necessary.
Also checking for available platform and device could be done in
`numba-dppy`. It also can raise and exception on import as before.
`dppl_present` also renamed to `dppy_present`.
Related to https://github.com/IntelPython/numba/pull/106
=> Move numba/dppl_config.py to numba_dppy/config.py

conda-recipe/meta.yaml
`dpNP` is not available for Windows yet.
Also, `numba-dppy` does not support osx.
=> Build with dpNP only on Linux

conda-recipe/run_test.bat, conda-recipe/run_test.sh, numba_dppy/__init__.py, numba_dppy/compiler.py, numba_dppy/testing.py, numba_dppy/tests/dppl/test_parfor_lower_message.py, numba_dppy/tests/dppl/test_prange.py, numba_dppy/tests/dppl/test_with_context.py
Test `test_parfor_message` skip unless GPU device is available.
But GPU device will be used only with `device_context`.
=> Fixing tests on CI

docs/dppy/device-functions.rst, docs/dppy/index.rst, docs/dppy/reduction.rst, docs/dppy/ufunc.rst, numba_dppy/examples/vectorize.py
=> Docs for Ufuncs

conda-recipe/meta.yaml
I did not find a way to use dpnp 0.4.0 but not 0.4.0=*_155. So I have to hardcode the last working package build number.
It is temporary solution to fix current CI.
=> Ignore specific dpnp package version

conda-recipe/bld.bat, conda-recipe/build.sh, conda-recipe/meta.yaml
- Add wheels build
- Use manylinux1 for Python 3.6
- Use manylinux2014 for Python > 3.6
=> Add wheels build + Update linux build tah for wheels

numba_dppy/dpnp_glue/dpnp_fptr_interface.pyx
dpnp 0.4.0=*_155 was removed from CI channels.
We will wait for dpnp 0.5.0 and will update to the new API.
=> Downgrade to dpnp 0.4.0=*_59

numba_dppy/tests/test_dpnp_functions.py
Unskip tests since problen with MKL is fixed in dpnp=0.5.0.  
Some tests still fail for several reasons:  
- test_gamma: Jitted function returns NoneType object
- test_multinomial: DPNP RNG Error: dpnp_rng_multinomial_c() failed
- test_multivariate_normal: Error with parameters
- test_negative_binomial: DPNP RNG Error: dpnp_rng_multinomial_c() failed
- test_uniform: TypeError with parameters
=> Unskip rng tests

CHANGELOG.md, README.md, conda-recipe/meta.yaml, conda-recipe/run_test.bat, conda-recipe/run_test.sh, pytest.ini
=> Run pytest in conda recipe

numba_dppy/dpnp_glue/dpnp_array_ops_impl.py, numba_dppy/dpnp_glue/dpnp_fptr_interface.pyx, numba_dppy/dpnp_glue/stubs.py, numba_dppy/rename_numpy_functions_pass.py, numba_dppy/tests/test_dpnp_functions.py
=> Implement np.sort in kernel by dpnp

numba_dppy/dppy_host_fn_call_gen.py, numba_dppy/examples/pa_examples/test1-2d.py, numba_dppy/examples/pa_examples/test1-3d.py, numba_dppy/examples/pa_examples/test1-4d.py, numba_dppy/examples/pa_examples/test1-5d.py, numba_dppy/examples/pa_examples/test1.py, numba_dppy/numpy_usm_shared.py, numba_dppy/ocl/atomics/__init__.py, numba_dppy/tests/test_no_copy_usm_shared.py
In the code that forms the kernel args, we now look to see if the array type is actually a USM shared type.  If so, we just place the data pointer directly into the kernel arg and so we avoid all the overhead of creating a new USM buffer and copying data there before the kernel and back afterwards.
=> Don't create a new copy of a usm shared array data pointers for kernel call.

README.md
Fixes #307.
I have moved long line in columns "Build Commands" to a line under the table.
Also I have found that the last line was incorrect.
=> Make Test Matrix table smaller

README.md, docs/index.rst, docs/user_guides/getting_started.rst, docs/user_guides/kernel_programming_guide/random.rst
using lower case for `dppy`, `dpnp`, `dpctl`. The style of camel casing just did not work with the masses.
=> Use correct names for other products dpctl, Numba, dpnp

conda-recipe/meta.yaml
This PR will restrict the dpnp version between >=0.5.1 and <0.6.*
=> Restrict dpnp version

conda-recipe/meta.yaml
Improves #344.
The problem with Python 3.8 is in integration with DPNP. So now I disable DPNP for Python 3.8 and downgrade DPNP to 0.5.1 on Python 3.7.
Enable it back in #348.
=> Fix dpnp version restriction in conda recipe

numba_dppy/dppy_lowerer.py, numba_dppy/tests/test_controllable_fallback.py, numba_dppy/tests/test_dppy_fallback.py, numba_dppy/tests/test_parfor_lower_message.py, numba_dppy/tests/test_with_context.py
Currently, when parfor lowering fails and we fall back to the default CPU lowerer for a parfor a very skimpy message is printed. The PR adds the traceback to get some more information on why and where DPPY lowering failed.
=> Print traceback when DPPY lowering failed.

numba_dppy/utils/__init__.py, numba_dppy/utils/llvm_codegen_helpers.py
- Helper function to get the LLVM type from numba types.
- A new helper class storing LLVM types for integers.
=> Adds a new utils submodule to provide LLVM IR builder helpers.

README.md, conda-recipe/meta.yaml, numba_dppy/dpnp_glue/dpnp_linalgimpl.py, numba_dppy/dpnp_glue/dpnp_statisticsimpl.py, numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
Currently available DPNP package is 0.6.0dev.
Closes #357 too, based on it.
=> Enable Python 3.8 with DPNP 0.6

numba_dppy/target.py
This PR adds `get_unfunc_info` to DPPYTargetContext. Without this function we can not offload `Numpy ufuncs` inside `@njit` decorated function. This was implemented in Numba 0.54.rc which was backported in Intel Numba [release0.53-patched](https://github.com/IntelPython/numba/tree/release0.53-patched).
=> Override get_ufunc_info in DPPYTargetContext

numba_dppy/compiler.py, numba_dppy/config.py, numba_dppy/spirv_generator.py
This PR only affects spirv validation (NUMBA_DPPY_SPIRV_VAL=1). It resolves the problem with not appropriate debug instruction name for offloading with ocl.
If we don't add "--spirv-debug-info-version=ocl-100" flag to spirv generating, we get the following error:
`error: line 9: Invalid extended instruction import 'SPIRV.debug'`
Add OpenCL.DebugInfo.100 as flag to SPIRV generator according to specification: https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.DebugInfo.100.html
=> Fix SPIR-V validation

numba_dppy/config.py
The PR improves the user warnings that are printed when a required version of `dpctl` is not found. There are three things that are checked for `numba_dppy` to set the `dppy_found` flag:
1. `import dpctl` does not raise an error.
2. The `dpctl` version is at least 0.7.0.
3. The `dpctl.select_default_device().is_host` returns `False`, *i.e.*, there is at least one non-host SYCL device.
Closes #219.
=> Improve error reporting when searching for dpctl.

numba_dppy/examples/blacksholes_kernel.py, numba_dppy/examples/blacksholes_njit.py
The examples are updated to use `dpctl.select_default_device()`.
=> Update blackscholes examples

numba_dppy/compiler.py, numba_dppy/tests/kernel_tests/test_caching.py
- Kernel caching based on SYCL queue no longer works as dpctl does not cache queues
globally. Instead, dpctl caches a default SYCL context for every root device.
- Changed the kernel caching logic in compiler.py accordingly and added a test case.
Closes #407
=> Fix kernel caching.

numba_dppy/__init__.py, numba_dppy/compiler.py, numba_dppy/decorators.py, numba_dppy/descriptor.py, numba_dppy/device_init.py, numba_dppy/dppy_lowerer.py, numba_dppy/dppy_passbuilder.py, numba_dppy/dppy_passes.py, numba_dppy/dufunc_inliner.py, numba_dppy/examples/matmul.py, numba_dppy/ocl/mathdecl.py, numba_dppy/ocl/mathimpl.py, numba_dppy/ocl/ocldecl.py, numba_dppy/ocl/oclimpl.py, numba_dppy/ocl/stubs.py, numba_dppy/printimpl.py, numba_dppy/target.py
Numba now only supports Python 3, we do not need the imports  from future any more in our sources as well.
=> Remove imports from future.

numba_dppy/dppy_lowerer.py, numba_dppy/ocl/ocldecl.py, numba_dppy/ocl/oclimpl.py, numba_dppy/ocl/stubs.py, numba_dppy/utils/__init__.py, numba_dppy/utils/constants.py, numba_dppy/utils/type_conversion_fns.py
- Moved the constant address space values to the utils module.
- Changed the name of all address spaces from "SPIR_*_ADDRSPACE"
to "GLOBAL", "LOCAL", etc. The change was done to make the
names in line with SYCL address spaces names rather than
SPIR-V address spaces.
- Added a type conversion function to convert npytypes.Array to
DPPYArray. The utility function is currently used only in
dppy_lowerer.py, but will be used in other places in future.
- Other cleanups such as removed commented out code and unused
imports.
This PR has some preliminary changes that will be used in the later PR to remove the kernel wrapper.
=> Refactored constants from target to utils.

numba_dppy/tests/test_debuginfo.py, numba_dppy/tests/test_dpnp_functions.py
Proposed improvements:
1. use `assert tag in ir` - it shows good explanation, but requires `tag` to be simple string
2. if RE not necessary then use simple strings
3. get `sycl_queue` from `dpctl.get_current_queue()` - device context is not necessary
4. test on default device - IR does not depend on device - 1 test instead of 3 tests
=> Tests improvements for debuginfo

docs/user_guides/debugging/breakpoints.rst, docs/user_guides/debugging/features.rst
Add documentation for breakpoints
=> Add docs for breakpoints

docs/index.rst, docs/user_guides/debugging/index.rst, docs/user_guides/debugging/set_up_machine.rst
Main page should provide tutorial with example where most useful features should be used.
Tutorial should contain end to end example of GDB usage.
=> Update debugging documentation main case

numba_dppy/compiler.py, numba_dppy/decorators.py, numba_dppy/tests/kernel_tests/test_return_type.py, numba_dppy/tests/njit_tests/dpnp/test_numpy_manipulation.py, numba_dppy/tests/test_debuginfo.py, numba_dppy/utils/__init__.py, numba_dppy/utils/misc.py
`@dppy.kernel` does not allow users to return anything. This PR adds checks to make sure this behavior is enforced and an useful error message is generated when users are trying to return from `dppy.kernel`
=> Raise error when users are trying to return from kernel

numba_dppy/compiler.py
This PR adds compiler flags that is needed for processing DWARF symbols generated by Numba-dppy.
=> Pass required compiler flags for processing genreated DWARF symbols

conda-recipe/build.sh, conda-recipe/meta.yaml, setup.py
Now dpcpp_linux-64 compiler is available on `-c intel`. It is not necessary to install oneAPI.
This PR uses dpcpp compiler package instead of using oneAPI.
Only for Linux.
=> Use dpcpp compiler package for Linux

conda-recipe/meta.yaml
This PR updates the runtime dependencies specified in the conda recipe.
1. Remove `llvmdev` as we do not use `opt` to generate LLVM bitcode.
2. Introduce `packaging` as it is being used in  `numba_dppy/config.py`.
@PokhodenkoSA Do we need to use packaging [here](https://github.com/IntelPython/numba-dppy/blob/main/numba_dppy/config.py#L17) or can it be accomplished somehow else?
=> Remove `llvmdev` from runtime dependecies

numba_dppy/compiler.py, numba_dppy/driver/usm_ndarray_type.py, numba_dppy/target.py, numba_dppy/tests/integration/test_usm_ndarray_interop.py
This PR will enable use of `dpctl.tensor.usm_ndarray` in Numba-dppy for functions decorated with `@dppy.kernel`.
=> Enable dpctl.tensor.usm_ndarray for @dppy.kernel

.github/workflows/license.yml
The latest update in go version is causing license step in CI to fail. This is an attempt to setup a version of go that will not fail to install license  using github action.
=> Update go version

.github/workflows/conda-package.yml, README.md, conda-recipe/meta.yaml
Conda recipe should restrict installation only `llvm-spirv 11`:
numba-dppy -> Numba 0.54 -> llvmlite 0.37.0 -> LLVM11
numba-dppy -> llvm-spirv 11 -> LLVM 11
Also:
=> Runtime dependency `llvm-spirv 11.*`

docs/user_guides/debugging/local_variables.rst, numba_dppy/examples/debug/sum_local_vars_revive.py
=> Add docs about local variables lifetime

conda-recipe/meta.yaml
I did not find a way to build with particular package. So I have to update the recipe.
It seems that dpnp 0.8.0dev0=_9 can not be used for building numba-dppy.
=> Update conda recipe dependency `dpnp 0.7*`

docs/user_guides/kernel_programming_guide/atomic-operations.rst, numba_dppy/config.py, numba_dppy/examples/atomic_op.py, numba_dppy/tests/kernel_tests/test_atomic_op.py
- Update typo in flag `NUMBA_DPPY_ACTIVATE_ATOMCIS_FP_NATIVE` -> `NUMBA_DPPY_ACTIVATE_ATOMICS_FP_NATIVE`.
- Update native atomic test.
=> Update test and fix typo

conda-recipe/conda_build_config.yaml
Proposed here:
https://github.com/numba/numba-examples/pull/39
=> Use older compiler for backwards compatibility

.github/workflows/generate-docs.yml, docs/conf.py
=> Add documentation workflow

numba_dppy/dpnp_glue/dpnp_linalgimpl.py
Change in DPNP introduced by https://github.com/IntelPython/dpnp/pull/930.
Pass pointer to array [1] for strides by default. Previously passed 0 pointer.
=> Fix passing strides array to DPNP dot and matmul.

numba_dppy/tests/test_debug_dppy_numba.py
It allows to see log of GDB interactions via command:
```bash
NUMBA_DPPY_DEBUG=1 pytest -q -s -ra --disable-warnings --pyargs numba_dppy -vv -k test_debug_dppy_numba
```
=> Use `NUMBA_DPPY_DEBUG` for debugging GDB tests

.github/release.yml, CHANGELOG.md
Added `.github/release.yml` file according to this documentation
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Also, assigned labels to PRs for generating better release notes.
Updated CHANGELOG.md with example of generated release notes.
Target to `release0.17` branch.
=> Improvements for automatically generated release notes

.github/workflows/generate-coverage.yml, README.md
This PR configures GitHub Actions to run tests with coverage and uploads the coverage results to coveralls.io [SAT-4655]
=> Run coverage in GitHub Actions and upload results to coveralls.io

conda-recipe/build.sh
DPC++ compiler package has new `llvm-spirv` location - `bin-llvm`.
=> Use llvm-spirv from bin-llvm during build

.git-blame-ignore-revs
Add the commit changing black line width to 80 to git-blame-ignore-revs file.
=> Ignore formatting changes from git-blame.

CHANGELOG.md, numba_dppy/config.py
=> Fix DeprecationWarning when use `version.parse()` [cherry picked from #639]

.github/workflows/conda-package.yml
The latest unreleased numba 0.55 package is not supported. It breaks CI. This PR pins package version with the latest supported package.
=> Pin numba 0.55 package for testing

conda-recipe/meta.yaml, conda-recipe/run_test.sh, numba_dppy/config.py, numba_dppy/spirv_generator.py
If `dpcpp` compiler package installed then `numba-dppy` uses `llvm-spirv` from it by default.
User could provide `LLVM_SPIRV_ROOT` to change it.
No need for defining 2 variables like here:
https://github.com/IntelPython/numba-dppy/blob/aa67724fc9a3175138264f36b034b9f8dc4a2efd/numba_dppy/examples/atomic_op.py#L33
=> Use `llvm-spirv` from `dpcpp` compiler package by default

CHANGELOG.md, conda-recipe/meta.yaml, conda-recipe/run_test.sh, numba_dppy/config.py, numba_dppy/spirv_generator.py
* Use llvm-spirv from dpcpp compiler package
* Fallback to llvm-spirv if dpcpp and LLVM_SPIRV_ROOT don't work
* Use llvm-spirv package for osx
* Print debug path to llvm-spirv
* Fix NUMBA_DPPY_LLVM_SPIRV_ROOT for Linux
* Add _llvm_spirv()
=> Use `llvm-spirv` from `dpcpp` compiler package by default [cherry picked from #649]

numba_dppy/tests/test_with_context.py
Missed check on existing device
Without level-zero:
```python
FAILED numba_dppy/tests/test_with_context.py::test_dpctl_device_context_affects_numba_pipeline[device_context0-level_zero:gpu:0] - V...
FAILED numba_dppy/tests/test_with_context.py::test_dpctl_device_context_affects_numba_pipeline[device_context1-level_zero:gpu:0] - V...
```
=> Fix skipping for Level Zero device for "with context" test

numba_dppy/tests/kernel_tests/test_atomic_op.py
=> Parameterize test for atomics

numba_dppy/tests/test_black_scholes.py, numba_dppy/tests/test_controllable_fallback.py, numba_dppy/tests/test_device_array_args.py, numba_dppy/tests/test_dpnp_functions.py, numba_dppy/tests/test_dppy_fallback.py, numba_dppy/tests/test_dppy_func.py, numba_dppy/tests/test_no_copy_usm_shared.py, numba_dppy/tests/test_offload_diagnostics.py, numba_dppy/tests/test_parfor_lower_message.py, numba_dppy/tests/test_prange.py, numba_dppy/tests/test_sum_reduction.py, numba_dppy/tests/test_with_context.py
Part of https://github.com/IntelPython/numba-dppy/pull/657
=> Reuse decorator `skip_no_opencl_Xpu` to skip tests

numba_dppy/tests/kernel_tests/test_atomic_op.py
Part of https://github.com/IntelPython/numba-dppy/pull/657
=> Add decorator to skip unsupported atomics

conda-recipe/meta.yaml, environment.yml, numba_dppy/dpctl_iface/usm_shared_allocator_ext.c, setup.py
=> Support dpctl 0.12

.github/workflows/conda-package.yml, conda-recipe/bld.bat, conda-recipe/conda_build_config.yaml, conda-recipe/meta.yaml, numba_dppy/tests/test_dpnp_iface.py, setup.py
Even if `dpnp` could be imported then importing `dpnp_fptr_interface` could fail.
`dpnp_fptr_interface` module could absent in conda package if `dpnp` was not imported during building.
`dpnp` could be not imported during building if wrong version of `mkl` was installed. 
`dpnp` package should pin correct version of `mkl`.
=> Fix building with DPNP

.github/workflows/conda-package.yml
New packages on `-c intel` was published. Now `dpctl 0.11.1 -c intel` is used for testing. It does not work with `dpcpp-cpp-rt 2021.3.0`.
`dpctl 0.11.1` does not control dependency on `dpcpp-cpp-rt` - https://github.com/IntelPython/dpctl/issues/727.
This PR makes testing w/ `dpctl 0.11.4` which is from `-c dppy/label/dev` and can work w/ `dpcpp-cpp-rt 2021.3.0`.
It is temporary solution.
=> Pin dpctl 0.11.4 [public CI]

.github/workflows/conda-package.yml, scripts/config_cpu_device.ps1
- Enable opencl cpu driver for work on device for Windows and Linux
- Change channels priority
- Pin dpctl versions on Windows
=> Fix public CI: opencl driver, channel priority, dpctl version

numba_dppy/initialize.py
Fixes #700.
Issue in dpctl: https://github.com/IntelPython/dpctl/issues/777
=> Load dpctl lib on Linux using `libDPCTLSyclInterface.so.0`

numba_dppy/spirv_generator.py
`shutil.which("dpcpp")` could return `None` and `os.path.dirname(dpcpp_path)` raises exception.
=> Fix search llvm-spirv if dpcpp compiler package is not installed

conda-recipe/meta.yaml
This PR adds `pytest-cov` requirement to test section of conda recipe for support coverege in internal CI.
=> Support for coverage in internal CI

conda-recipe/conda_build_config.yaml, conda-recipe/meta.yaml
Update recipe to fix internal CI
=> Update recipe with dpctl and dpnp version for build

setup.py
Previously you had to add `bin-llvm` to `PATH`: `export PATH=$CONDA_PREFIX/bin-llvm:$PATH`. See `conda-recipe`.
Now `setup.py` can find `llvm-spirv` using path to `dpcpp`.
=> Search `llvm-spirv` for `setup.py` in folder `bin-llvm`

.flake8, .pre-commit-config.yaml, numba_dppy/compiler.py, numba_dppy/core/passes/lowerer.py, numba_dppy/core/passes/passes.py, numba_dppy/dppy_passbuilder.py
In preparation for the renaming from numba_dppy to numba_dpex, the PR renames the modules `dppy_lowerer` and `dppy_passes` to just `lowerer` and `passes`. The goal is to reduce the usage of `DPPY` or `numba_dppy` prefixes as much as possible to easy the name change.
=> Remove DPPY prefix for modules and functions in numba_dppy.core.passes.

numba_dppy/dpctl_iface/usm_allocators_ext.c, numba_dppy/dpnp_ndarray/models.py, numba_dppy/numpy_usm_shared.py, numba_dppy/tests/njit_tests/dpnp_ndarray/runtime/test_usm_allocators_ext.py, numba_dppy/tests/njit_tests/dpnp_ndarray/test_boxing.py, numba_dppy/tests/njit_tests/dpnp_ndarray/test_models.py, numba_dppy/tests/njit_tests/dpnp_ndarray/test_typeof.py, setup.py
=> Fix remarks for `dpnp.empty()` #728

docs/conf.py
Use `"sphinx.ext.intersphinx"` extension to generate site objects inventory used for cross-linking.
Rendered site should contain `objects.inv` file with the required data.
=> Use intershphinx extension to generate inventory data for cross-linking

conda-recipe/bld.bat, conda-recipe/build.sh, conda-recipe/meta.yaml
Updated run-time dependencies of `numba-dpex` to require `dpctl >=0.13` given binary incompatibility of `dpctl` v0.12 and `dpctl` v0.13
=> Update dependencies for 2022.2

numba_dpex/examples/sum_reduction_recursive_ocl.py, numba_dpex/tests/integration/DuckUSMArray.py, numba_dpex/tests/integration/test_sycl_usm_array_iface_interop.py, numba_dpex/tests/test_array_utils.py
This PR adjusts `numba_dpex` tests to create `DuckUSMArray` using the same queue.
This solves tests failures:
```
FAILED test_sycl_usm_array_iface_interop.py::test_kernel_valid_usm_obj[i4] - Failed: Could not pass Python object with sycl_usm_array_interface to a kernel.
FAILED test_sycl_usm_array_iface_interop.py::test_kernel_valid_usm_obj[i8] - Failed: Could not pass Python object with sycl_usm_array_interface to a kernel.
FAILED test_sycl_usm_array_iface_interop.py::test_kernel_valid_usm_obj[f4] - Failed: Could not pass Python object with sycl_usm_array_interface to a kernel.
FAILED test_sycl_usm_array_iface_interop.py::test_kernel_valid_usm_obj[f8] - Failed: Could not pass Python object with sycl_usm_array_interface to a kernel.
```
Kernels could not launch due to strengthened check in …
=> Fix tests for intefration sycl usm array interface

.github/workflows/conda-package.yml, conda-recipe/meta.yaml, docs/user_guides/getting_started.rst, environment.yml, environment/coverage.yml, environment/docs.yml, numba_dpex/dpnp_iface/dpnp_array_ops_impl.py, numba_dpex/dpnp_iface/dpnp_fptr_interface.pyx, numba_dpex/tests/njit_tests/dpnp/test_numpy_array_ops.py
DPNP map of kernel functions for take() was updated in scope of [#1172](https://github.com/IntelPython/dpnp/pull/1172): an input array of indices has to be of an integer type. For other types of indices data, DPNP backend function get_dpnp_function_ptr() will raise a runtime exception pointing on the types mismatching.
Numba-DPEX had missing "except +" notation while declaring get_dpnp_function_ptr() in cython file. Thus the exception from DPNP backend led to a core dump in Numba-DPEX instead of printing the error.
Numba-DPEX shall explicitly pass a type of input array for indices while calling DPNP backend, rather than passing "None". It will help to select a proper kernel function, since DPNP has to know how incoming array is placed in the memory to avoid any potential memory corruption …
=> Fix a crash when calling take() for input array with non-integer values

.github/workflows/conda-package.yml
The recent crash in the `dpnp_take` function has been fixed in the version of dpnp uploaded to the `dppy/label/dev` conda channel. The PR uses the dpnp and dpctl versions available in `dppy/label/dev` to build and test numba-dpex in the GitHub CI.
=> Use dpctl and dpnp from dppy/label/dev and remove pinning on specific dpctl and dpnp versions

numba_dpex/compiler.py, numba_dpex/core/descriptor.py, numba_dpex/core/passes/lowerer.py, numba_dpex/core/target.py, numba_dpex/device_init.py, numba_dpex/dpctl_iface/usm_ndarray_type.py, numba_dpex/dpnp_ndarray/models.py, numba_dpex/numpy_usm_shared.py, numba_dpex/offload_dispatcher.py, numba_dpex/retarget.py, numba_dpex/spirv_generator.py
Moves the `numba_dpex.target` and `numba_dpex.descriptor` modules into `numba_dpex.core` sub-module and update all impacted imports.
The eventual goal of these incremental changes is to move all the compiler machinery into `core`.
=> Move target.py and descriptor.py into the core module.

numba_dpex/examples/pairwise_distance.py
Updates the pairwise_distance.py PR to ensure it works on devices that do not provide double precision support.
=> Fixed pairwise_distance.py to run on machine with no FP64 support in HW

.pre-commit-config.yaml
Fixes the broken flake8 workflow by updating the git repo for the pre-commit hook from gitlab to hithub.
=> Fix flake8 pre-commit hook.

.github/workflows/conda-package.yml, numba_dpex/examples/debug/simple_dpex_func.py, numba_dpex/examples/debug/simple_sum.py, numba_dpex/examples/debug/sum_local_vars.py, numba_dpex/examples/debug/sum_local_vars_revive.py, numba_dpex/examples/select_device_for_kernel.py
1. Added running numba dpex examples as part of workflow. 
2. Switched to select_default_device() to pass CI.
3. Disabled two examples: vectorize.py and usm_ndarray.py which are failing. Investigation will be made in separate PR (#807 & #838 ).
=> Added examples to github workflow.

docs/user_guides/kernel_programming_guide/synchronization.rst, numba_dpex/device_init.py, numba_dpex/examples/kernel_private_memory.py, numba_dpex/examples/sum_reduction_ocl.py, numba_dpex/examples/sum_reduction_recursive_ocl.py, numba_dpex/ocl/oclimpl.py, numba_dpex/ocl/stubs.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_barrier.py, numba_dpex/tests/kernel_tests/test_private_memory.py
- [Y ] Have you provided a meaningful PR description?
- [N] Have you added a test, reproducer or referred to an issue with a reproducer?
- [N] Have you tested your changes locally for CPU and GPU devices?
- [Y] Have you made sure that new changes do not introduce compiler warnings?
- [N] If this PR is a work in progress, are you filing the PR as a draft?
=> Removed CLK_ prefix from mem fences

docs/developer_guides/caching.rst, numba_dpex/codegen.py, numba_dpex/config.py, numba_dpex/core/caching.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/kernel_interface/spirv_kernel.py, numba_dpex/decorators.py, numba_dpex/tests/kernel_tests/test_caching.py
- This PR addresses issue #814 
- This PR implements an LRU cache mechanism for numba_dpex.
- The LRU cache can pickle kernels if they are evicted.
- This PR is rebased on top of https://github.com/IntelPython/numba-dpex/commit/26c4334b1ef0b08ade41c5ca301c528ca2e9aa79
- This PR supercedes #815 and #833
TODO:
=> A new LRU cache mechanism for numba_dpex with kernel pickling capability

conda-recipe/meta.yaml, numba_dpex/config.py, numba_dpex/device_init.py
There are API changes in dpctl 0.14.1dev1 to accommodate changes in dpcpp 2023.0. Specifically, `dpctl.SyclDevice` no longer has the `is_host` property. The change impacts the check inside `numba_dpex.config._dpctl_has_non_host_device` that was throwing an uncaught `AttributeError`.
The PR fixes the issue by using only `dpctl.select_default_device()`. Also the minimum dpctl version required was bumped to 0.14.
=> Bump dpctl version requirement to 0.14 and fix issue caused by API change

numba_dpex/core/exceptions.py, numba_dpex/core/kernel_interface/dispatcher.py
- Removes superfluous copy inside JitKernel.__getitem__
- Improves the JitKernel._check_range and JitKernel._check_ranges
methods. We now check if a range is empty and if a well-formed
global range was provided.
- Minor fixes to error messages (typos, etc.)
- Add missing docstrings to numba_dpex.core.exceptions classes.
=> Fixes to checking validity of a range.

numba_dpex/spirv_generator.py, setup.py
numba-dpex does not pin the max-spirv-version that `llvm-spirv` generates and lets `llvm-spriv` decide what SPIR-V code to generate based on the LLVM-IR generated by the Numba front-end.
The behaviour is causing an issue with oneAPI dpcpp 2023.0 (Refer #868). The issue arises when a pre-compiled SPIR-V binary produced by compiling an OpenCL program implementing software atomic add for floating point values is linked to the SPIR-V module generated by JIT compilation inside numba-dpex.
The PR implements a workaround by setting the `spirv-max-version` flags to 1.1 when generating SPIR-V both for the pre-compiled OpenCL program and inside numba-dpex. SPIR-V version 1.1 is used as it seems to be the default used by dpcpp.
=> Set the max spirv version to 1.1

numba_dpex/utils/llvm_codegen_helpers.py
The PR fixes few minor typos in docstring comments in `llvm_codegen_helper.py`
=> Fix typos in comments.

.github/workflows/black.yml, .pre-commit-config.yaml, numba_dpex/core/passes/dufunc_inliner.py, numba_dpex/core/passes/lowerer.py, numba_dpex/core/passes/passes.py, numba_dpex/core/passes/rename_numpy_functions_pass.py, numba_dpex/dpnp_iface/dpnp_linalgimpl.py, numba_dpex/examples/kernel/kernel_specialization.py, numba_dpex/examples/kernel/vector_sum.py, numba_dpex/numpy_usm_shared.py, numba_dpex/ocl/ocldecl.py, numba_dpex/tests/kernel_tests/test_kernel_launch_params.py, numba_dpex/tests/kernel_tests/test_kernel_specialization.py
Numba-dpex now uses black 23.1 and the PR updates the pre-commit config and reformat the files impacted by the change.
=> Updates the black requirement to black 23.1

numba_dpex/core/targets/dpjit_target.py, numba_dpex/decorators.py
Updates the dpjit decorator to be a shim over Numba's jit decorator and only change the Pipeline. The pipeline is presently the OffloadPipeline that may change in the future.
Also update the `DpexTargetContext` to inherit from `CPUContext` instead of `BaseContext`.
No, as no real functionality has been added and the work is mostly stubs.
Yes
=> Updates to the dpjit decorator and dpjit target context

numba_dpex/core/datamodel/models.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/tests/kernel_tests/test_dpnp_ndarray_args.py
- Changes the `DpexKernelTypingContext` to always use the `to_usm_ndarray` utility function to convert `dpnp.ndarray`
arguments to a `UsmNdArray` type.
- The change allows passing `dpnp.ndarrays` correctly to kernels without impacting dpjit functions.
- Fixes numba_dpex/examples/kernel/interpolation.py
=> Changes to allow dpnp.ndarray objects as kernel arguments.

numba_dpex/core/passes/passes.py, numba_dpex/core/pipelines/kernel_compiler.py, numba_dpex/tests/kernel_tests/test_func_qualname_disambiguation.py, numba_dpex/tests/test_debuginfo.py
Fixes #898. 
Please refer to the issue for more details.
=> @func decorator qualname ambiguation fix

.github/workflows/conda-package.yml
The issue will cause example test run fail due to missing -name.
=> Fixed a minor issue when running example tests in conda-package.yml.

numba_dpex/core/caching.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/tests/kernel_tests/test_arg_types.py, numba_dpex/tests/test_device_array_args.py
This PR might solve issue #886. 
In version 0.19.0, the `create_program_from_spirv()` was done only once. See [line 483](https://github.com/IntelPython/numba-dpex/blob/0.19.0/numba_dpex/compiler.py#L483) in `compiler.py`.
In the current main it's been done everytime when `__call__()` function was invoked from `JitKernel` (See [here](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/core/kernel_interface/dispatcher.py#L630)). Therefore we are now caching the `kernel_bundle` to avoid the repeated call of `create_program_from_spirv()`.
=> Solving perferomance regression issue by caching the kernel_bundle

numba_dpex/__init__.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/kernel_interface/indexers.py, numba_dpex/core/kernel_interface/utils.py, numba_dpex/tests/kernel_tests/test_kernel_launch_params.py, numba_dpex/tests/kernel_tests/test_kernel_specialization.py, numba_dpex/tests/kernel_tests/test_ndrange_exceptions.py
- The compute follows data related functions are required in parfor lowering as well. The PR moves the two functions `determine_kernel_launch_queue` and `chk_compute_follows_data_compliance` out of kernel_interface/dispatcher.py into kernel_interface/utils.py and makes them public.
- The Range and NdRange classes are moved to kernel_interface/indexers.py
=> Move CFD-related fucntions to a separate module.

numba_dpex/config.py, numba_dpex/dpctl_support.py
If dpctl was built from source without `.git` folder present, `dpctl.__version__` is `0+unknown` and `dpctl_version` computation in `numba_dpex/dpctl_support.py` broke down. 
Introduced function to safely infer `dpctl_version`, and modified `config.py` to issue soft `logging.warning` about unmet dpctl version instead of raising hard `ImportError`.
=> Replace ImportError with logging.warning if dpctl version is not met

numba_dpex/dpctl_support.py, numba_dpex/tests/test_dpctl_api.py
Added hastily remove slicing of dpctl version tuple to the first two elements which are expected to be integral.
=> Fixed a blunder in _parse_version

numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/context.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_ones.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros.py
Once completed, this PR will supercede PR #743.
=> Implementing dpnp.zeros() and dpnp.ones() interface

numba_dpex/config.py, numba_dpex/core/kernel_interface/spirv_kernel.py, numba_dpex/tests/test_dump_kernel_llvm.py
Adding functionality to output LLVM IR to a file. The output file name contains a hash generated from the LLVM module name. This allows us to write different kernels to separate files since the hash is expected to be unique.
Tested with Blackscholes in dpbench. File name generated is `llvm_kernel_ce84b7ebc25a6c5f71403d77de797be75067dce745a14ae28ca34dc5e3365998.ll`
Tested on GPU
=> Output LLVM IR if NUMBA_DPEX_DEBUG environment variable is set

numba_dpex/core/codegen.py, numba_dpex/core/runtime/context.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/dpctl_iface/dpctl_capi_fn_builder.py, numba_dpex/ocl/oclimpl.py, numba_dpex/printimpl.py, numba_dpex/utils/llvm_codegen_helpers.py
The llvmlite.llvmpy module has been deprecated and is slotted for removal with the next llvmlite release. The PR updates our source code to remove all usage of llvmlit.llvmpy and replace it with corresponding functionality from llvmlite.ir.
No, but all existing tests have been verified.
=> Removes the usage of llvmlite.llvmpy

numba_dpex/dpnp_iface/_intrinsic.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_ones_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros_like.py
1. Implementation for overloading `dpnp.empty_like()`, `dpnp.zeros_like()` and `dpnp.ones_like()` type of functions.
2. This also does code-reorganization in [`arrayobj.py`](https://github.com/IntelPython/numba-dpex/blob/main/numba_dpex/dpnp_iface/arrayobj.py)
=> Implementation for dpnp.empty_like(), dpnp.zeros_like() and dpnp.ones_like()

numba_dpex/core/kernel_interface/indexers.py
=> Fix bug with indexers.py, errors need to be 'raised'

.flake8, numba_dpex/core/passes/parfor.py, numba_dpex/core/passes/passes.py
Back ports the new Parfor pass from https://github.com/numba/numba/pull/8725
- Splits the parfor pass into separate Parfor, ParforFusion
and ParforPreLowering passes.
- Introduces a "lowerer" attribute into parfor nodes to help
use different lowerers based on compute follows data
programming model.
=> Backported the split parfor pass from upstream Numba.

numba_dpex/core/types/dpnp_ndarray_type.py
- Added the __array_ufunc__ function that propagates the type of any array expression involving DpnpNdArray as DpnpNdArray. The method is primarily meant as an aid to help the ParforLegalizeCFDPass later in the pipeline.
- Added __allocate__ function that generates the Numba IR to allocate a new instance of DpnpNdArray.
Tests will be added in follow up PRs as these functionality need other changes to be fully usable.
=> Extends the DpnpNdArray type.

numba_dpex/core/runtime/_dpexrt_python.c
Closes gh-965 by raising Python exception when `arraystruct->meminfo` field is null, and unhandled exception would have caused dereferencing of the null pointer and subsequent crash.
=> Handle the case when arraystruct->meminfo is null to close gh-965

.dockerignore, .github/workflows/docker.yml, Dockerfile, docs/index.rst, docs/user_guides/docker.rst, docs/user_guides/getting_started.rst, scripts/github_load.py
Add Dockerfile both for runtime and building with and without gpu drivers
Workflow will produce these docker tags:
https://github.com/ZzEeKkAa?tab=packages&repo_name=numba-dpex
Action result can be found here:
https://github.com/ZzEeKkAa/numba-dpex/actions/runs/4473683752
There where few issues that prevented docker from building:
- dpctl was not compiling on Debian based machine (fixed in dpctl repo)
- latest graphics drivers fail numba_dpex test for kernel that tries to print from GPU
Fixes #933
=> Add Dockerfile and workflow

.github/workflows/conda-package.yml, CHANGELOG.md, conda-recipe/meta.yaml, conda-recipe/run_test.sh, docs/user_guides/getting_started.rst, docs/user_guides/kernel_programming_guide/atomic-operations.rst, environment.yml, environment/coverage.yml, environment/docs.yml, numba_dpex/config.py, numba_dpex/spirv_generator.py, setup.py
=> Replaced llvm_spirv from oneAPI path by dpcpp-llvm-spirv package.

.github/workflows/conda-package.yml
In CI, shell scripts are executed with elevated priviledges, hence OpenCL loader ignores variable OCL_ICD_FILENAMES. One must set a registry value. intel-opencl-rt comes with a script to do that.
It also comes with fixed cl.cfg file, so the step to modify cl.cfg in situ is no longer needed, and in fact corrupts the file.
=> Adjusting test_windows step to work with intel-opencl-rt=2023.1.0

numba_dpex/core/types/usm_ndarray_type.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty.py
- numba-dpex's usm_ndarray type relies on dpctl.tensor to determine the default dtype for an array. In the constructor for the usm_ndarray type, there was a typo that was causing an exception in dpjit when dpnp.empty or other constructor was called without a dtype.
- Adds a unit test case.
=> Fix typo in the keyword argumnet when constructing a tensor.

CHANGELOG.md
=> Updated CHANGELOG.md for 0.20.1 release.

numba_dpex/core/compiler.py
The `OffloadCompiler` is deprecated and set to be removed in 0.21. Instead, we now have two separate pipelines `DpjitCompiler` and `KernelCompiler` to compile `dpjit` and `kernel` decorated functions respectively.
The PR changes the `compiler.py` implementation to use the `KernelCompiler` when compiling kernels generated as numba function IR from parfor nodes. 
Existing test cases for parfor and dpjit should not break after the change.
=> Use kernel compiler for parfors as well.

numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/context.py, numba_dpex/core/types/usm_ndarray_type.py, numba_dpex/dpnp_iface/_intrinsic.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_ones_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros_like.py
Implementation for `dpnp.full()`.
This will enable calling `dpnp.full()` inside `@dpjit` functions.
=> Implementation for dpnp.full()

numba_dpex/dpnp_iface/_intrinsic.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full_like.py
Implementation for `dpnp.full_like()`.
This will enable calling `dpnp.full_like()` inside `@dpjit` functions.
=> Implementation for dpnp.full_like()

numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_nrt_helper.c, numba_dpex/core/runtime/_nrt_python_helper.c
Numba package updated syntax for `nrt_debug_print`, which caused issues on compilation time. This PR renames function in order to be able to compile for both versions of numba and be more reliable on numba updates.
https://github.com/IntelPython/numba-dpex/issues/1000
=> Rename nrt_debug_print -> drt_debug_print

numba_dpex/core/descriptor.py, numba_dpex/core/targets/dpjit_target.py, numba_dpex/core/targets/kernel_target.py
For some reason it is no longer available via `numba.core.utils` import. Anyway, it looks like clean up change.
https://github.com/IntelPython/numba-dpex/issues/1000
~UPD: there are few places to face similar issue.~
=> Replace parent package for cached_property import

numba_dpex/core/runtime/_dbg_printer.h, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_nrt_helper.c, numba_dpex/core/runtime/_nrt_python_helper.c
- Fixes build error after the nrt_dbg_print was renamed to
drt_debug_print.
=> Move the declaration of drt_debug_print into a header.

environment/coverage.yml
Changes the order in which channels are searched when installing packages for the coverage workflow. The change should allow us to get latest dpctl and dpnp packages from `dppy/label/dev`
=> Change the order of channels in coverage's environment yaml

numba_dpex/core/typeconv/array_conversion.py, numba_dpex/core/types/usm_ndarray_type.py, numba_dpex/core/typing/typeof.py
Using queue cached by `dpctl` for `USMNdArray` type.
Potentially fixes #945
=> Using cached queue instead of creating new one on type inference

numba_dpex/tests/kernel_tests/test_atomic_op.py
This PR makes the necessary changes to make test_atomic_op testcase follow "Compute Follows Data" semantics. 
- The input numpy ndarray declaration is changed to dpnp array. 
- All uses of dpctl.device_context has been removed. Filter strings are now passed directly to dpnp array allocation.
- Kernel invocations now use dpex.Range classes for specifying global and local size.
Fixes #986. Tested on 4th gen Xeon. Tests run on CPU with OpenCL backend and on GPU with level zero
=> Making test_atomic_op testcase CFD compliant

numba_dpex/core/passes/parfor_lowering_pass.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/tests/dpjit_tests/test_dpjit_complex_arg_types.py
=> Enabled complex number in dpjit.

.github/workflows/conda-package.yml
Changes how pytest is invoked in the test_linux and test_windows workflows. using `python -m pytest` leads to directories that do not have `__init__.py` in them getting skipped. The difference in invocation was the cause we see different results in coverage v/s test package workflows.
=> Directly invoke pytest in package build workflow.

numba_dpex/config.py, numba_dpex/core/passes/parfor_lowering_pass.py, numba_dpex/core/pipelines/kernel_compiler.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/context.py, numba_dpex/core/utils/kernel_builder.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/core/utils/kernel_templates/kernel_template_iface.py, numba_dpex/core/utils/kernel_templates/reduction_template.py, numba_dpex/core/utils/reduction_helper.py, numba_dpex/core/utils/reduction_kernel_builder.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/dpjit_tests/test_dpjit_reduction.py
1. New config to run the ConstantSizeStaticLocalMemoryPass optionally.
2. Adds support for prange reduction loops to numba-dpex.
- Adds a template to generate a tree-reduction kernel for reduction loops that use the "+" or "*" operators.
- Adds code generation for nd-range kernels in the parfor lowerer.
- Refactoring of the parfor lowerer and kernel builder modules.
- New unit test cases.
=> Enable dpnp parfor reduction

numba_dpex/core/utils/kernel_templates/reduction_template.py, numba_dpex/tests/dpjit_tests/test_dpjit_reduction.py
1. Fixed a bug in reduction template generation for multiplication.
2. Added a unite test.
=> Fixed bug in reduction mul operation for dpjit.

numba_dpex/core/runtime/_nrt_python_helper.c, numba_dpex/core/runtime/_nrt_python_helper.h
Enables building numba_dpex with Python 3.11.
Fixes #1052
=> support Python 3.11

numba_dpex/spirv_generator.py, numba_dpex/tests/kernel_tests/test_print.py
As #885 , spirv-max-version is limited to 1.1 to avoid with oneAPI dpcpp 2023.0. While infra team is updating spirv headers to 1.4, as part of Numba 0.57 upgrade, numba-dpex needs to lift the limit and support spirv 1.4.
=> Upgraded spirv-max-version from 1.1 to 1.4.

setup.py
Updates the spirv version used to compile the atomic emulation kernel to bring it in line with the changes introduced in #1056
=> Update the SPIR-V version for the atomic emulation kernel.

numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/parfors/reduction_kernel_builder.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/typeconv/array_conversion.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/core/types/usm_ndarray_type.py, numba_dpex/core/typing/typeof.py, numba_dpex/dpnp_iface/_intrinsic.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/core/types/DpctlSyclQueue/test_queue_ref_attr.py, numba_dpex/tests/core/types/USMNdArray/test_array_creation_errors.py, numba_dpex/tests/core/types/USMNdArray/test_usm_ndarray_creation.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty_like.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_bitwise_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_logic_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_transcedental_functions.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_trigonometric_functions.py, numba_dpex/tests/dpjit_tests/test_dpjit_reduction.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_barrier.py, numba_dpex/tests/kernel_tests/test_caching.py, numba_dpex/tests/kernel_tests/test_scalar_arg_types.py, numba_dpex/tests/test_array_utils.py, numba_dpex/tests/test_vectorize.py, setup.py
Storing the Python dpctl.SyclQueue inside any instance of the DpctlSyclQueue type was causing segfaults due to the Python object getting garbage collected prematurely.
The changes in the PR update the DpctlSyclQueue type to only store the filter string associated with the dpctl.SyclQueue and not the actual Python object. In addition, the USMNdArray type now stores an instance of a DpctlSyclQueue in its queue parameter instead of a Python dpctl.SyclQueue object.
Due to these changes, all places where the Python dpctl.SyclQueue was getting extracted and used from a UsmNdArray instance or DpctlSyclQueue instance have been updated.
All test cases were also updated.
=> Changes to the DpctlSyclQueue and USMNdArray types.

numba_dpex/tests/core/types/DpctlSyclQueue/test_queue_ref_attr.py, numba_dpex/tests/core/types/USMNdArray/test_array_creation_errors.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_bitwise_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_logic_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_transcedental_functions.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_trigonometric_functions.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_barrier.py, numba_dpex/tests/kernel_tests/test_caching.py, numba_dpex/tests/test_array_utils.py, numba_dpex/tests/test_vectorize.py, setup.py
- Add fveclib=none to the compile flags in setup.py. The flag ensures that icx does not try to link with SVML.
=> Various fixes to get numba-dpex build on the internal TeamCity CI/CD

numba_dpex/tests/dpjit_tests/parfors/test_dpnp_logic_ops.py
Removes xfail for unit tests that actually pass
=> Passing tests are incorrectly marked xfail.

conda-recipe/run_test.bat, conda-recipe/run_test.sh, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/types/dpnp_ndarray_type.py, numba_dpex/core/types/usm_ndarray_type.py, numba_dpex/tests/core/passes/test_parfor_legalize_cfd_pass.py
Update conda-recipe tests to run on every cpu and gpu sycl selector.
Skip failing tests
=> Fix jenkins CI

numba_dpex/core/itanium_mangler.py
This PR resolves a broken hyperlink found in the `core/itanium_mangler.py` file. This is because the C++ ABI repository 
moved from [`MentorEmbedded/cxx-abi`](https://github.com/MentorEmbedded/cxx-abi) to [`itanium-cxx-abi/cxx-abi`](https://github.com/itanium-cxx-abi/cxx-abi) (see README file of [`MentorEmbedded/cxx-abi`](https://github.com/MentorEmbedded/cxx-abi)). You can find this broken hyperlink in the docs [here](https://intelpython.github.io/numba-dpex/latest/apidoc/numba_dpex.core.itanium_mangler.html).
=> fix: update Itanium CXX ABI Mangler reference

docs/user_guides/debugging/backtrace.rst, docs/user_guides/debugging/breakpoints.rst, docs/user_guides/debugging/stepping.rst
This PR resolves Sourceware resources in different files. Instead of `https://sourceware.org/gdb/current/onlinedocs/*` it should be `https://sourceware.org/gdb/onlinedocs/*`.
=> fix: update sourceware resources

.github/workflows/docker.yml, Dockerfile
Add `dpcpp-llvm-spirv` support. Update some build instructions to work with newer versions. Upgrade dep versions.
Update base image to use debian bookworm. It unblocks from using latest gpu drivers and it seems like the problem with print inside gpu kernel is gone.
=> Update docker to support recent changes

numba_dpex/core/targets/kernel_target.py
In KernelTarget's `resolve_argument_type` we convert `DpnpNdArray` type arguments to `USMNdArray`. Previously, the conversion was done using the `__sycl_usm_array_interface__` via Python. The PR changes to only do a type conversion from `DpnpNdArray` to `USMNdArray` without having to introspect the `__sycl_usm_array_interface__` dictionary.
Not needed as existing tests check for the functionality.
=> Simplify DpnpNdArray to USMNdArray conversion during kernel argument resolution.

numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/tests/dpjit_tests/parfors/prange/test_pairwise_distance.py
A typo in the parfor_lower module was resulting in improper data model lookup for prange arguments. The PR fixes the issue.
Yes
Yes
=> Fix typo causing improper datamodel lookup.

numba_dpex/core/codegen.py, numba_dpex/core/kernel_interface/spirv_kernel.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/core/types/usm_ndarray_type.py
Fixes how function names are generated at the LLVM IR level for `numba_dpex.kernel` decorated functions and auto-generated kernels for parfor nodes.
Previously an unreadable gobbledegook was generated
> dpex_py_devfn__5F__5F_main_5F__5F__2E_kernel_5F_vector_5F_sum_24_1_2E_USMNdArray_28_dtype_3D_float64_2C__20_ndim_3D_1_2C__20_layout_3D_C_2C__20_address_5F_space_3D_1_2C__20_usm_5F_type_3D_device_2C__20_device_3D_level_5F_zero_3A_gpu_3A_0_2C__20_sycl_5F_queue_3D_DpctlSyclQueue_29__2E_USMNdArray_28_dtype_3D_float64_2C__20_ndim_3D_1_2C__20_layout_3D_C_2C__20_address_5F_space_3D_1_2C__20_usm_5F_type_3D_device_2C__20_device_3D_level_5F_zero_3A_gpu_3A_0_2C__20_sycl_5F_queue_3D_DpctlSyclQueue_29__2E_USMNdArray_28_dtype_3D_float64_2C__20_ndim_3D_1_2C__20_layout_3D_C_2C__20_address_5F_space_3D_1_2C_ …
=> Generate proper mangled name for kernel functions

numba_dpex/core/datamodel/models.py, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/tests/core/types/DpnpNdArray/test_models.py
Previously, a `dpnp.ndarray` argument passed to a `kernel` function was passed as an instance of `numba_dpex.core.types.USMNdArray`. The `USMNdArray` type uses the `numba_dpex.core.datamodel.models.USMArrayModel` data model where pointers have an explicit address space qualifier.
The PR now registers the `dpnp.ndarray`-specific `DpnpNdArray` types with a `USMArrayModel` for the `DpexKernelTarget` and with the `numba.core.datamodel.models.ArrayModel` for the `CPUTarget`. By doing so, we now correctly recognize a `dpnp.ndarray` passed to a kernel as such instead of a generic `USMNdArray` object. The change unblocks the creation of a Numba-specific CPython wrapper for kernel functions as we need to use the correct Numba type to properly unbox and box a `dpnp.ndarray`.
Additionally, fixes a …
=> Use different data models for DpnpNdArray Type for kernel and dpjit targets

CMakeLists.txt, MANIFEST.in, conda-recipe/meta.yaml, environment.yml, environment/coverage.yml, numba_dpex/CMakeLists.txt, numba_dpex/core/runtime/CMakeLists.txt, numba_dpex/tests/core/types/__init__.py, pyproject.toml, setup.py
We need to switch to scikit-build based setup. 
This will make easy to integrate/compile different extensions and libraries with orthogonal requirements.
JIRA Reference: [SAT-6040](https://jira.devtools.intel.com/browse/SAT-6040)
=> scikit-build setup.py for numba-dpex

docs/source/getting_started.rst, environment/docs.yml
=> Update docs for scikit-build

.github/workflows/conda-package.yml, .github/workflows/docker.yml, build-environment.yml, numba_dpex/core/runtime/_nrt_python_helper.c
Python 3.8 is no longer officially supported.
Fixes #1114
=> Do not build for python 3.8 in Github CI

CMakeLists.txt, numba_dpex/core/runtime/CMakeLists.txt
Remove deprecated FindPythonLibs dependencies since they are no longer supported by CMake 3.27.
~~Blocked by https://github.com/IntelPython/dpctl/pull/1389~~
Close #1125
=> Remove deprecated FindPythonLibs

.github/workflows/conda-package.yml
Most of the packages from intel are now available on conda-forge, but they behave differently as for now. OpenCL runtime is not the exception. Pining this version to intel channel solves problem with CI, but we should investigate why does not it work with conda-forge channel and report related issue.
=> Pin CI conda channels

.github/workflows/coverity.yml, README.md
Initial PR to support Open Source Coverity Reports. I was able to run this workflow on a fork and it successfully uploaded basic build. Now the project needs to be reviewed by the Coverity:
```
While we review your project application you cannot view defects.
It takes about 1-2 business day to review your association with the project and to make sure project meets open source guidelines.
```
`cov-analyze` not available in the toolset right now. I'm not sure if we suppose to run it for open source here or just set up it in project settings.
=> Add Coverity scan CI

setup.py
All rc and dev tags was unable to build
=> Fix cmake version convertion

numba_dpex/core/typing/typeof.py
Renames the `_typeof_helper` function in `numba_dpex.core.typing.typeof.py` to clearly indicate that it applies only to the DpnpNdArray and UsmNdArray types.
=> Rename helper function to clearly indicate its usage

numba_dpex/tests/_helper.py, numba_dpex/tests/core/passes/test_parfor_legalize_cfd_pass.py, numba_dpex/tests/core/types/DpnpNdArray/test_boxing_unboxing.py, numba_dpex/tests/core/types/USMNdArray/test_array_creation_errors.py, numba_dpex/tests/core/types/USMNdArray/test_usm_ndarray_type.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_ones.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_ones_like.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_zeros_like.py, numba_dpex/tests/dpjit_tests/parfors/test_builtin_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_logic_ops.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_transcedental_functions.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_trigonometric_functions.py, numba_dpex/tests/dpjit_tests/test_dpjit_complex_arg_types.py, numba_dpex/tests/dpjit_tests/test_dpjit_reduction.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_complex_array.py, numba_dpex/tests/kernel_tests/test_math_functions.py, numba_dpex/tests/kernel_tests/test_scalar_arg_types.py, numba_dpex/tests/kernel_tests/test_sycl_usm_array_iface_interop.py, numba_dpex/tests/kernel_tests/test_usm_ndarray_interop.py, numba_dpex/tests/test_prange.py
Most of the integrated GPUs does not support doble precision and numba by default uses double precision floats. That makes our tests fail on those GPUs. This changes targeted to add support for tests on single precision GPUs by:
- tests that where using default allocation or only float64/complex128 uses were patched to use float32/complex64 implementations;
- tests that accept dtype parameters where patched to run only on supported types
- few issues where found with lowering or silent crashes. Those tests were patched to bypass these cases.
Discovered issues:
- `arctan2` does not work for `float32` if device does not support `float64` (silent crash)
- `parfor_divide` and `parfor_exponent` does not work on `int32` and `int64` if device does not support `float64` (lowering error)
Issue …
=> Support tests on single point precision GPUs

numba_dpex/core/datamodel/models.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_eventstruct.h, numba_dpex/core/runtime/context.py, numba_dpex/core/types/__init__.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/core/typing/typeof.py, numba_dpex/tests/core/types/DpctlSyclEvent/__init__.py, numba_dpex/tests/core/types/DpctlSyclEvent/test_box_unbox.py, numba_dpex/tests/core/types/DpctlSyclEvent/test_models.py
Add dpctl.SyclEvent to numba friendly types, so that we can convert kernel dispatcher into @dpjit function.
Closes: #1137
=> Add sycl event

numba_dpex/core/datamodel/models.py, numba_dpex/core/kernel_interface/indexers.py, numba_dpex/core/types/__init__.py, numba_dpex/core/types/range_types.py, numba_dpex/core/typing/typeof.py, numba_dpex/tests/core/types/range_types/__init__.py, numba_dpex/tests/core/types/range_types/test_constructor_overloads.py, numba_dpex/tests/core/types/range_types/test_data_model.py, numba_dpex/tests/core/types/range_types/test_unbox_box.py
- The numba_dpex.core.kernel_interface.indexers.Range and
NdRange classes can now be used inside a numba_dpex.dpjit
decorated function, as arguments to a dpjit decorated function,
and returned from a dpjit decorated function.
- Defines a datamodel, type class, overloads for the constructors,
box, and unbox functions for both classes.
~~The PR should be merged post 0.21.3 tag~~
=> Adds Range and NdRange as supported types in numba_dpex.dpjit.

numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/tests/core/types/DpnpNdArray/test_boxing_unboxing.py
- When boxing a dpnp.ndarray using the reference of the parent
stored during unboxing, there is a validation step on the strides.
However, as a dpnp.ndarray object does not store any stride
information when an array is unit strided the strides need to be
calculated and validated against the strides in the Numba
usmarraystruct object.
The PR fixes the stride calculation that was previously done
incorrectly.
=> Fixes bug in boxing a DpnpNdArray from parent.

numba_dpex/config.py, numba_dpex/core/codegen.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/tests/misc/test_warnings.py
It appears that level 3 optimization breaks kernel execution, so we need to set default value to 2 (which seems to work acceptable). This is a quick fix for #1152 and further investigation needed.
=> Add DPEX_OPT, INLINE_THRESHOLD config and do not use numba's OPT

numba_dpex/core/types/range_types.py
Adds the `ndim` attribute to the `name` attribute of `RangeType` and `NdRangeType`. It makes the `__str__` for these types show a more informative string.
=> Improve __str__ for range_types

numba_dpex/core/descriptor.py, numba_dpex/core/kernel_interface/func.py, numba_dpex/core/kernel_interface/spirv_kernel.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/spirv_generator.py
Adds initial set of changes to make enable creating a new `Dispatcher` sub-type in numba-dpex to compile kernel decorated functions. The changes in this PR are mostly lightweight refactoring.
=> Cleanups to kernel target

.github/workflows/conda-package.yml, conda-recipe/bld.bat, conda-recipe/build.sh
Wheels are uploaded to the version from wheels package that comes from versioner. That version is different for wheel and Conda and contains GitHub stash. That results into junk in Conda registry version list. PR simply uploads same wheel to the version of Conda package.
=> Upload wheel to the same version

numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/parfors/reduction_helper.py, numba_dpex/core/pipelines/kernel_compiler.py, numba_dpex/core/utils/kernel_launcher.py
- Changes to the kernel_launcher.KernelLaunchIRBuilder  class constructor to make it easier to use from
places other than the parfor_lowerer. Removed the need to pass a lowerer object and instead pass a context and builder.
- Adds a new helper function populate_kernel_args_and_args_ty_arrays that populates arrays storing kernel args and kernel 
arg types.
- We should not generate a cpython or a cfunc wrapper for a kernel decorated function.
- The no_compile is also set to True as the kernel LLVM IR will not be compiled to an executable object code by Numba.
Instead, numba-dpex will compile the LLVM IR to SPIR-V and generate a sycl::kernel_bundle.
=> Miscellaneous changes to compiler internals

.flake8, .pre-commit-config.yaml, numba_dpex/core/itanium_mangler.py, numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/parfors/reduction_helper.py, numba_dpex/core/targets/dpjit_target.py, numba_dpex/decorators.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/examples/blacksholes_njit.py, numba_dpex/numba_patches/patch_arrayexpr_tree_to_ir.py, numba_dpex/numba_patches/patch_mk_alloc.py, numba_dpex/ocl/mathdecl.py, numba_dpex/ocl/mathimpl.py, numba_dpex/ocl/ocldecl.py, numba_dpex/parfor_diagnostics.py, numba_dpex/tests/core/types/test_box_unbox.py, numba_dpex/tests/debugging/test_breakpoints.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full.py, numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_full_like.py, numba_dpex/tests/kernel_tests/test_usm_ndarray_interop.py, numba_dpex/vectorizers.py
Add extra check for the pre-commit and remove commented code.
=> Add flake8 eradicate

numba_dpex/__init__.py, numba_dpex/core/datamodel/models.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/core/typing/typeof.py, numba_dpex/dpctl_iface/_intrinsic.py, numba_dpex/tests/core/types/DpctlSyclEvent/test_models.py, numba_dpex/tests/core/types/DpctlSyclEvent/test_overloads.py
Add `dpctl.SyclEvent.wait()` overload for `dpjit` functions.
Closes: #1138
=> Add sycl event wait overload

numba_dpex/core/datamodel/models.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_eventstruct.h, numba_dpex/core/runtime/_nrt_helper.c, numba_dpex/core/runtime/_nrt_helper.h, numba_dpex/core/runtime/context.py, numba_dpex/dpctl_iface/libsyclinterface_bindings.py
Memory lifetime wasn't set properly which resulted in core dumps of running kernels if boxed sycl event argument where destroyed by GC. New implementation wraps parent into `MemInfo` object and lifetime of the object is managed by it which is properly managed by numba's compiler.
P.S. : also fixed functions signature for dpctl sycl binding.
=> Fix lifetime management for sycl event

numba_dpex/core/datamodel/models.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_queuestruct.h, numba_dpex/core/runtime/context.py
Memory lifetime wasn't set properly which resulted in core dumps of running kernels if boxed sycl event argument where destroyed by GC. New implementation wraps parent into `MemInfo` object and lifetime of the object is managed by it which is properly managed by numba's compiler.
Similar changes to https://github.com/IntelPython/numba-dpex/pull/1188
Closes https://github.com/IntelPython/numba-dpex/issues/1180
=> Fix lifetime management for sycl queue

numba_dpex/core/runtime/_dpexrt_python.c
Fixes compiler warnings generated due to assignment from incompatible pointer types.
Yes
Fixes #1202
=> Fixes -Wincompatible-pointer-types in dpex_rt_python.c

numba_dpex/experimental/decorators.py, numba_dpex/tests/experimental/test_exec_queue_inference.py
Fixes compilation with the experimental kernel decorator using `NUMBA_CAPTURED_ERROR=new_style`
Fixes #1195
=> Add experimental kernel decorator to numba jit_registry

.github/workflows/conda-package.yml, numba_dpex/tests/debugging/test_backtraces.py, numba_dpex/tests/debugging/test_breakpoints.py, numba_dpex/tests/debugging/test_common.py, numba_dpex/tests/debugging/test_info.py, numba_dpex/tests/debugging/test_side_by_side.py, numba_dpex/tests/debugging/test_stepping.py
Added gdb tests for CI and mark the failing tests as xfail or skip.
Closes #1189
=> Added gdb tests in CI

numba_dpex/core/datamodel/models.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/_eventstruct.c, numba_dpex/core/runtime/_eventstruct.h, numba_dpex/core/runtime/context.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/dpctl_iface/_intrinsic.py, numba_dpex/dpctl_iface/libsyclinterface_bindings.py, numba_dpex/tests/core/types/DpctlSyclEvent/test_box.py, numba_dpex/tests/core/types/DpctlSyclQueue/test_box.py, numba_dpex/tests/dpjit_tests/test_slicing.py
Introduce a way to define sycl event inside dpjit and return it back to python.
- `SyclEvent()` is overloaded.
- `syclevent_to_python` handles structures without parent.
- datamodel was extended to have parent (same as in sycl queue).
PR checks:
Closes: #1184
=> Add sycl event constructor overload

numba_dpex/experimental/decorators.py, numba_dpex/experimental/kernel_dispatcher.py, numba_dpex/experimental/launcher.py, numba_dpex/experimental/models.py, numba_dpex/experimental/target.py
- The experimental target is now fully separated from the `DpexKernelTarget` with a different string identifier and device class.
- A clone of the DpexKernelTarget's datamodel manager is added that will store all experimental types' data models till they are ready to move into core.
=> Register the experimental kernel target as a fully standalone Numba hardware target

numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/experimental/launcher.py
Code restructuring to achieve encapsulation and simplify logic. Some comments where added for easier navigation.
It is not perfect, but better than it was
=> Clean up experimental launcher

numba_dpex/core/codegen.py, numba_dpex/core/descriptor.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/experimental/decorators.py, numba_dpex/experimental/kernel_dispatcher.py, numba_dpex/tests/experimental/codegen/__init__.py, numba_dpex/tests/experimental/codegen/test_inline_threshold_codegen.py, numba_dpex/tests/experimental/test_compiler_warnings.py, numba_dpex/tests/experimental/test_inline_threshold_config.py, numba_dpex/tests/experimental/test_target_specific_overload.py
Add a new `device_func` decorator to compile `DpexKernelTarget` overloads 
- A new `generate_device_ir` option for `DpexTargetDescriptor` is introduced. The new option can be used to prevent a module to be compiled to device IR binary.
- A new `device_func` decorator that is registered to compile overloads in `DpexExpKernelTarget`. The `device_func` decorated
functions are not compiled to device IR.
- The `kernel` decorator is updated to compile a finalized module to device IR.
=> Enables adding overload to DpexExpKernelTarget and fully inline them into the final module.

numba_dpex/core/runtime/CMakeLists.txt
Link numpy libraries as python submodule instead of linking it as a standalone package. This the second and the last PR to enable VSCode cpp integration via CMake toolset plugin. First one (https://github.com/IntelPython/dpctl/pull/1484)
Old way of integration seems to be outdated and for some strange reason was not working in vscode.
=> Use NumPy as python sublibrary in cmake

numba_dpex/core/exceptions.py, numba_dpex/experimental/__init__.py, numba_dpex/experimental/flag_enum.py, numba_dpex/experimental/kernel_dispatcher.py, numba_dpex/experimental/launcher.py, numba_dpex/experimental/literal_intenum_type.py, numba_dpex/experimental/models.py, numba_dpex/experimental/target.py, numba_dpex/tests/experimental/IntEnumLiteral/test_compilation.py, numba_dpex/tests/experimental/IntEnumLiteral/test_type_creation.py, numba_dpex/tests/experimental/IntEnumLiteral/test_type_registration.py, numba_dpex/tests/experimental/codegen/test_intenum_literal_codegen.py
- Adds a new `IntEnumLiteral` type with corresponding data model into the `DpexExpKernelTargetContext`.
The type is used to pass in or define an `IntEnum` flag as an `numba.types.IntegerLiteral` inside a kernel function.
=> Adds a new literal type to store IntEnum as Literal types.

conda-recipe/meta.yaml, environment.yml, environment/coverage.yml, environment/docs.yml, environment/pre-commit.yml
2024.0.1 dpcpp conda package is broken. Until it is resolved, let's merge this workaround
=> Workaround: pin dpcpp version to 2024.0.0

numba_dpex/experimental/kernel_iface/__init__.py, numba_dpex/experimental/kernel_iface/memory_enums.py, numba_dpex/tests/experimental/kernel_iface/__init__.py, numba_dpex/tests/experimental/kernel_iface/test_memory_enum_compilation.py
The PR adds a new `kernel_iface` module to `numba_dpex.experimental` and a Python representation of dpcpp/SYCL's memeory enum classes. The three new Enum classes: `MemoryScope`, `MemoryOrder`, `AddressSpace` derive from `FlagEnum` and can be used as Literal flags in an experimental kernel.
=> Adds memory enum classes to the experimental module

.pre-commit-config.yaml, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/parfors/reduction_helper.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/experimental/launcher.py
Update kernel launcher builder to use builder pattern. Since the argument list is long we need modular way of providing those arguments to make code more readable and extendable.
=> Apply builder pattern to kernel launcher

numba_dpex/core/utils/kernel_launcher.py, numba_dpex/experimental/launcher.py
Changes:
- Get rid of `CallKernelBuilder` and extend `KernelLaunchIRBuilder`. 
- call_kernel and call_kernel_async now uses same function to generate IR
- call_kernel no longer allocates meminfo for event_ref
Checklist:
=> Extend kernel launcher

numba_dpex/experimental/kernel_dispatcher.py
The `impl_kind` class attribute was removed from numba's `Dispatcher` class in 0.59.0rc1. The `_compiler` attribute for `Dispatcher` is now always set to numba's `_FunctionCompiler` class.
To accommodate for these changes, `numba_dpex.experimental.dispatcher.KernelDispatcher` will conditionally set its `_compiler` attribute to the `_KernelCompiler` class when numba version in use is >0.59, otherwise will default to old behaviour.
- [] Have you added a test, reproducer or referred to an issue with a reproducer?
=> Changes to KernelDispatcher to support numba 0.59

numba_dpex/experimental/kernel_dispatcher.py
Allow target specific overload. Tested manually at https://github.com/IntelPython/numba-dpex/pull/1252
=> Enable target specific overloads in experimental kernel

numba_dpex/core/exceptions.py, numba_dpex/spirv_generator.py
Instead of reporting a command line with randomly generated filenames and exit code, returns an output (both stdout and stderr) from `dpcpp-llvm-spirv` tool. Uses numba style error.
Before:
```
numba_dpex/tests/kernel_tests/test_atomic_op.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
numba_dpex/core/kernel_interface/dispatcher.py:455: in __call__
) = self._compile_and_cache(
numba_dpex/core/kernel_interface/dispatcher.py:141: in _compile_and_cache
kernel.compile(
numba_dpex/core/kernel_interface/spirv_kernel.py:171: in compile
self._device_driver_ir_module = spirv_generator.llvm_to_spirv(
numba_dpex/spirv_generator.py:240: in llvm_to_spirv …
```
=> Improve spirv error reporting in numba

numba_dpex/core/kernel_interface/dispatcher.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_barrier.py, numba_dpex/tests/kernel_tests/test_caching.py, numba_dpex/tests/kernel_tests/test_kernel_launch_params.py
The existing `numba_dpex.kernel` functions can be launched by providing either a `Range` or `NdRange` object to `numba_dpex.core.kernel_interface.dispatcher.JitKernel.__getitem__`, or the global and local sizes as lists or tuples. The use of list and tuples was deprecated a while back. This PR removes the deprecated support and now only `Range` or `NdRange` arguments are supported as kernel launch parameters.
No, but existing tests have been fixed and updated.
Fixes #1040
=> Removes the deprecated feature of providing kernel launch params as lists and tuple

numba_dpex/experimental/decorators.py, numba_dpex/experimental/kernel_dispatcher.py, numba_dpex/experimental/launcher.py, numba_dpex/tests/experimental/test_kernel_specialization.py
- Add support for eager compilation for experimental kernel by providing type signature.
- Test cases where taken from kernel and adopted for experimental kernel style call. During this process it was discovered that experimental kernel can't work with dpctl tensors as arguments.
- Some code from kernel was adopted to experimental kernel
Checklist
=> Add eager experimental kernel compilation

numba_dpex/__init__.py, numba_dpex/core/kernel_interface/launcher.py, numba_dpex/tests/kernel_tests/test_atomic_op.py, numba_dpex/tests/kernel_tests/test_barrier.py, numba_dpex/tests/kernel_tests/test_complex_array.py, numba_dpex/tests/kernel_tests/test_dpnp_ndarray_args.py, numba_dpex/tests/kernel_tests/test_func.py, numba_dpex/tests/kernel_tests/test_func_specialization.py, numba_dpex/tests/kernel_tests/test_invalid_kernel_args.py, numba_dpex/tests/kernel_tests/test_kernel_has_return_value_error.py, numba_dpex/tests/kernel_tests/test_kernel_specialization.py, numba_dpex/tests/kernel_tests/test_math_functions.py, numba_dpex/tests/kernel_tests/test_ndrange_exceptions.py, numba_dpex/tests/kernel_tests/test_print.py, numba_dpex/tests/kernel_tests/test_private_memory_allocation.py, numba_dpex/tests/kernel_tests/test_scalar_arg_types.py, numba_dpex/tests/kernel_tests/test_sycl_usm_array_iface_interop.py, numba_dpex/tests/kernel_tests/test_usm_ndarray_interop.py, numba_dpex/tests/misc/test_warnings.py
Add `call_kernel` for the outdated kernel to make transfer to experimental kernel smoother.
Easy way to update usage (not perfect, but would work with trivial cases):
```regexp
([A-Za-z_\(\)]*)\[(.*Range.*)\]\((.*)\)
dpex.call_kernel($1, $2, $3)
```
=> Add call_kernel for the old kernel

numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/types/dpctl_types.py, numba_dpex/experimental/__init__.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/__init__.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_spv_atomic_inst_helper.py, numba_dpex/experimental/dpcpp_types.py, numba_dpex/experimental/kernel_iface/__init__.py, numba_dpex/experimental/kernel_iface/atomic_ref.py, numba_dpex/experimental/launcher.py, numba_dpex/experimental/models.py, numba_dpex/experimental/typeof.py, numba_dpex/spirv_generator.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/__init__.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/test_atomic_fetch_phi.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/test_atomic_ref.py
Adds a new `AtomicRef` class to the experimental `kernel_iface` module to mimic `sycl::atomic_ref` class. The class includes Python functions to simulate the atomic `fetch_*` functions in SYCL.
The `AtomicRef` class is also overloaded and an overloaded implementation is provided for the class constructor and the `fetch_add` method was also added.
UPD: one bug was introduced/discovered along with a workaround: https://github.com/IntelPython/numba-dpex/issues/1262
=> Overloads for an AtomicRef class and fetch_add method

numba_dpex/core/datamodel/models.py, numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/types/dpnp_ndarray_type.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/experimental/kernel_dispatcher.py, numba_dpex/tests/core/types/DpnpNdArray/test_models.py, numba_dpex/tests/core/types/test_box_unbox.py, numba_dpex/tests/experimental/test_supported_array_types_as_kernel_args.py
Add support for `dpctl.tensor.usm_ndarray` to dpjit and experimental kernel.
Several additional changes where made:
- Apply better naming for `USMNdArray`/`DpnpNdArray` data models.
- Fix for `USMNdArray` device data model.
- Use same data type for host and separate type for device for both `USMNdArray` and `DpnpNdArray`
Checklist
=> Add dpctl tensor support

numba_dpex/examples/kernel/pipelining.py
Add example from the issue https://github.com/IntelPython/numba-dpex/issues/147#issuecomment-1871595286 to the examples  repo folder.
=> Add pipelining example

numba_dpex/core/targets/dpjit_target.py, numba_dpex/core/targets/kernel_target.py, numba_dpex/dpnp_iface/dpnp_ufunc_db.py, numba_dpex/tests/test_dpex_use_alongside_numba.py
Add tests to ensure that `numba.njit` works with `numpy` after importing `numba_dpex`. Aka lazy testing if we break `numba`'s default behavior.
Fixes: #1010
=> Create dpnp specific ufunc db

numba_dpex/core/kernel_interface/indexers.py, numba_dpex/core/targets/dpjit_target.py, numba_dpex/dpctl_iface/_intrinsic.py, numba_dpex/dpnp_iface/_intrinsic.py, numba_dpex/dpnp_iface/arrayobj.py, numba_dpex/experimental/launcher.py, numba_dpex/experimental/testing.py, numba_dpex/tests/core/types/DpctlSyclQueue/test_queue_ref_attr.py, numba_dpex/tests/dpjit_tests/dpnp/test_target_specific_overload.py, numba_dpex/tests/dpjit_tests/test_dpex_target_overload_isolation.py
Make overloads and intrinsic target specific, so we don't accidentally break numba.
=> Make overloads and intrinsic target specific

numba_dpex/tests/experimental/test_strided_dpnp_array_in_kernel.py
This PR confirms the new experimental kernel can correctly handle strided dpnp arrays.
This PR closes issue #572 and supercedes #1268
=> Tests for multi-dimensional multi-level strided dpnp arrays in (experimental) kernel

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/spirv_generator.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/test_atomic_fetch_phi.py
Adds the remaining overloads for `fetch_*` functions to the `_atomic_ref_overloads` module. These include - fetch_sub, fetch_min, fetch_max, fetch_and, fetch_or, and fetch_xor.
This PR also contains positive and negative test cases for testing out each of the atomic functions
=> Adds all fetch_* SPIR-V overload to experimental

numba_dpex/tests/experimental/test_strided_dpnp_array_in_kernel.py
1. Strided array correctly works with the current code.
2. This PR performs unit test for all situations (differing dimensions, shape, strides, view-of-views etc.)
3. This PR performs unit test for both `C` and `F` contiguous arrays.
4. This is relevant to the experimental kernel, will not work with the old kernel code.
This PR finally resolves #572 and supersedes #1268 and #1271
Fixes #572, #363
=> Refactor all tests for strided dpnp arrays in kernel with different layouts

docs/source/user_guide/kernel_programming/writing_kernels.rst, docs/source/user_guide/programming_model.rst, numba_dpex/__init__.py, numba_dpex/vectorizers.py
Remove the `DEFAULT_LOCAL_SIZE` from the codebase.
This fixes #1273
=> Remove DEFAULT_LOCAL_SIZE completely from the code

.github/workflows/conda-package.yml, conda-recipe/meta.yaml, environment.yml, environment/coverage.yml, environment/docs.yml, environment/pre-commit.yml
Enable the usage of dpcpp_linux-64 2024.1 package to build numba-dpex
=> Allow use of latest dpcpp compiler package

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/spv_fn_generator.py, numba_dpex/experimental/kernel_iface/atomic_ref.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/test_atomic_cmp_exchg.py, numba_dpex/tests/experimental/kernel_iface/spv_overloads/test_atomic_load_store.py
This PR adds overloads and intrinsics for load, store and exchange atomic operations. It also contains unit tests that verify the functionality and the failure cases for these operations.
=> Implementations for atomic load, store and exchange operations

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/literal_intenum_type.py, numba_dpex/experimental/target.py, numba_dpex/kernel_api/flag_enum.py, numba_dpex/kernel_api/memory_enums.py, numba_dpex/tests/experimental/IntEnumLiteral/test_compilation.py, numba_dpex/tests/experimental/IntEnumLiteral/test_type_creation.py, numba_dpex/tests/experimental/IntEnumLiteral/test_type_registration.py, numba_dpex/tests/experimental/codegen/test_intenum_literal_codegen.py
Moves the `FlagEnum` class from `numba_dpex.experimental` to `kernel_api`.
=> Move FlagEnum into kernel_api.

numba_dpex/experimental/__init__.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_group_barrier_overloads.py, numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/barrier.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_barriers.py
This PR contains implementation of group_barrier function that synchronizes across all work-items in a work group. It also contains a test case to verify the functionality of the barrier call.
=> Implementation of group barrier operation

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/spv_fn_generator.py, numba_dpex/kernel_api/atomic_ref.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_load_store_cmp_exchg.py
This PR contains the implementation of compare_exchange_strong and compare_exchange_weak atomic functions. It contains a test case that verifies both success and failure scenarios.
=> Atomic compare_exchange implementation

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_group_barrier_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_index_space_id_overloads.py, numba_dpex/experimental/core/types/kernel_api/items.py, numba_dpex/experimental/models.py, numba_dpex/experimental/typeof.py, numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/barrier.py, numba_dpex/kernel_api/index_space_ids.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_barriers.py
Adds Group class that is mock for the `sycl::group`. Adds corresponding numba type with empty struct data model to avoid any allocations, since it is just typing feature. As a result barriers can be used only at NdRanges, which is aligned with sycl.
=> Add Group and overload NdItem.get_group()

numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/index_space_ids.py, numba_dpex/kernel_api/launcher.py, numba_dpex/kernel_api/ranges.py, numba_dpex/tests/kernel_api/__init__.py, numba_dpex/tests/kernel_api/test_ndrange_kernel_launch.py, numba_dpex/tests/kernel_api/test_range_kernel_launch.py
Extends the mock `kernel_api.Group` class to add group index functions.
Adds implementation for launching Range and NdRange kernels in pure Python.
=> Extends mock kernel API by more group index functions and adds launchers

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_index_space_id_overloads.py, numba_dpex/kernel_api/index_space_ids.py, numba_dpex/tests/experimental/test_index_space_ids.py
Enables the following group indexing functions inside a kernel:
`get_group_id`
`get_group_range`
`get_local_range`
=> Adds overloads for group indexing functions

docs/.gitignore, docs/Makefile, docs/_static/css/custom.css, docs/_templates/autoapi/index.rst, docs/_templates/autoapi/macros.rst, docs/_templates/autoapi/python/attribute.rst, docs/_templates/autoapi/python/class.rst, docs/_templates/autoapi/python/data.rst, docs/_templates/autoapi/python/exception.rst, docs/_templates/autoapi/python/function.rst, docs/_templates/autoapi/python/method.rst, docs/_templates/autoapi/python/module.rst, docs/_templates/autoapi/python/package.rst, docs/_templates/autoapi/python/property.rst, docs/source/api_reference/index.rst, docs/source/conf.py, docs/source/index.rst, environment/docs.yml
Adds initial support for generating API documentation.
=> Adds API Documentation infrastructure

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_group_barrier_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/spv_atomic_fn_declarations.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_load_store_cmp_exchg.py
This PR fixes the failure that was occurring `opencl:cpu` when atomic load, store and exchange operations were being used. Spirv expects arguments to be of integer types always. This PR introduces a `bitcast` to integer types when the argument are of floating point types.
This PR also added additional function attributes to these atomic function declarations, keeping it the same as the declaration generated for DPC++.
It further updates the test cases to remove expected failure on `opencl:cpu` executions.
=> Fix for atomic load, store, exchange failure on ocl

conda-recipe/meta.yaml, environment/coverage.yml, environment/docs.yml, environment/pre-commit.yml
Bumps the minimum version requirements for `dpcpp`, `dpctl`, `numba`, `dpnp` in meta.yaml and all environment files.
=> Update dependent package pinning to newer versions.

numba_dpex/experimental/__init__.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_fence_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_group_barrier_overloads.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/spv_fn_declarations.py, numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/atomic_fence.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_fence.py
This PR contains implementation of atomic_fence function that orders loads and stores across all work-items specified in the call. It also contains a test case to verify the functionality of atomic_fence.
Also added is a commit containing a minor typo fix in group_barrier overload implementation
=> Implementing atomic_fence in dpex.kernel

numba_dpex/tests/dpjit_tests/parfors/test_builtin_ops.py
Skips the `ipow` parfor tests even on Level Zero gpu devices.
=> Skip ipow tests on L0 GPU.

numba_dpex/core/utils/kernel_launcher.py, numba_dpex/tests/experimental/test_index_space_ids.py
Adds alignment for array allocations inside `call_kernel`. This resolves failing tests, that was triggering errors due to array overflows or something like this (first value of array type got overwritten to 0 in some test cases). Seems like alignment solved the problem, but further investigations are required.
Fixes https://github.com/IntelPython/numba-dpex/issues/1308
=> Add kernel launcher array allocation alignment

numba_dpex/experimental/launcher.py
Renames helper functions to make the private so as to not get show up in public API documentation.
=> Makes helper functions private.

.github/workflows/conda-package.yml
Windows tests started failing since `8.0.2` pytest release. Use previous version
Pytest issue to track the status: https://github.com/pytest-dev/pytest/issues/12036
=> Pin pytest to 8.0.1

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/kernel_api/atomic_ref.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_fence.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_ref.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_barriers.py
Previous implementation used to work only with flat indexes. This one accept multidimentional indexes.
Question: Should we remove default value for the index? It will cause `TypeError` on 2- and 3-dimentional arrays?
=> Accept multidimentional atomic indexes

conda-recipe/meta.yaml
Exclude `dpcpp` 2024.0.3 along with 2024.0.1 and 2024.0.2 on windows.
Motivated by https://github.com/IntelPython/dpctl/pull/1578
- n/a Have you added a test, reproducer or referred to an issue with a reproducer?
- n/a Have you tested your changes locally for CPU and GPU devices?
- n/a Have you made sure that new changes do not introduce compiler warnings?
=> Block 2024.0.3 dpcpp packages

numba_dpex/experimental/__init__.py, numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_private_array_overloads.py, numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/private_array.py, numba_dpex/kernel_api_impl/spirv/arrayobj.py, numba_dpex/tests/experimental/test_private_array.py
Creates `PrivateArray` class that is used inside `kernel_api`. Overloaded with `USMNdArray` instance generation on stack.
=> Add PrivateArray kernel_api

numba_dpex/dpctl_iface/_helpers.py
https://github.com/IntelPython/dpctl/pull/1581 updated the enum values for DPCTLSyclKernelArgTy and also introduced a Python enum to track the libsyclinterface values. The current numba-dpex PR uses the latest API and enum from dpctl if the semantic version of dpctl is 0.17 or greater. Old behavior is retained for backward compatibility.
=> Use enum values for kernel arg types if dpctl >= 0.17

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py
Some of the experimental SPIR-V overloads such as the AtomicRef overloads try to set needed SPIR-V extensions flags only for a module that uses such an overload. However, the functionality is broken (see https://github.com/IntelPython/numba-dpex/issues/1262) and needs deeper design changes than are warranted.
We are unconditionally adding needed SPIR-V extension flags in the `spirv_generator` module. The solution is adequate for now and perhaps should be *THE* long-term solution.
This PR removes the essentially dead code of adding extra SPIR-V extension flags inside AtomicRef overloads.
=> Do not selectively apply spirv exts unconditionally do so in spirv_generator

numba_dpex/tests/_helper.py, numba_dpex/tests/experimental/test_index_space_ids.py
Run indexing functions tests both through numba and python simulator
=> Extend indexing function tests to kernel simulator

numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_barriers.py, numba_dpex/tests/experimental/test_private_array.py
The existing `func` decorator has several design limitation that does not allow usage of features such as `barrier`, `dpex.local.array` and `dpex.private.array` inside a `func` decorated function. These limitations reduced the utility of the feature. See: https://github.com/soda-inria/sklearn-numba-dpex/blob/747914481371ee7fe6527240a7bb57104d207115/sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py#L142
All these limitations are addressed by the new `experimental.device_func` decorator. The PR adds unit tests to verify that `kernel_api.global_barrier` and `kernel_api.PrivateArray` can be used in a `device_func` decorated function.
=> Verify global_barrier, indexing, private array inside device_func

numba_dpex/core/datamodel/models.py, numba_dpex/core/types/kernel_api/local_accessor.py, numba_dpex/core/utils/kernel_flattened_args_builder.py, numba_dpex/core/utils/kernel_launcher.py, numba_dpex/dpctl_iface/_helpers.py, numba_dpex/experimental/__init__.py, numba_dpex/experimental/launcher.py, numba_dpex/experimental/models.py, numba_dpex/experimental/typeof.py, numba_dpex/kernel_api/__init__.py, numba_dpex/kernel_api/launcher.py, numba_dpex/kernel_api/local_accessor.py, numba_dpex/tests/experimental/codegen/test_local_accessor_kernel_arg.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_local_accessors.py, numba_dpex/tests/kernel_api/test_local_accessor.py
The PR adds a `sycl::local_accessor` like API to numba-dpex's kernel API.
TODOs
=> A sycl::local_accessor-like API for numba-dpex kernel

numba_dpex/kernel_api_impl/spirv/dispatcher.py, numba_dpex/tests/experimental/test_kernel_has_return_value_error.py
The KernelHasReturnValueError check was not working as intended in the experimental module. The PR fixes it by moving the check after compilation and using the signature as derived by the compilation result.
=> Fix KernelHasReturnValueError inside KernelDispatcher.

numba_dpex/tests/_helper.py, numba_dpex/tests/dpjit_tests/parfors/test_dpnp_ufuncs.py
We had a left over use of `dpctl.device_context` in our test suite. Now that the `device_context` context manager has been fully removed from dpctl, the public Github CI was failing. The PR updates numba-dpex's source to not use the `device_context`.
=> Fix use of dpctl.device_context in tests

numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py, numba_dpex/kernel_api/atomic_ref.py, numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_ref.py
- Verifies that an AtomicRef can be constructed from a LocalAccessor object in both kernel_api and compiled modes.
- Change the default value of the AddressSpace keyword to AtomicRef overload to None. If the value is None, it gets inferred from the ref argument. Doing this we do not have to explicitly specify AddressSpace value for AtomicRef constructed from a LocalAccessor.
- Unit tests.
=> Verify that AtomicRef over LocalAccessor is supported.

numba_dpex/core/utils/kernel_launcher.py, numba_dpex/experimental/launcher.py
Add gdb support to experimental kernel. Tests for gdb are currently broken, so nothing was added right now
=> Add no optimization flags when debugging is on for experimental kernel

numba_dpex/tests/kernel_tests/test_complex_array_kernel_arg.py, numba_dpex/tests/kernel_tests/test_dpnp_ndarray_args.py, numba_dpex/tests/kernel_tests/test_func.py, numba_dpex/tests/kernel_tests/test_func_qualname_disambiguation.py, numba_dpex/tests/kernel_tests/test_invalid_kernel_args.py, numba_dpex/tests/kernel_tests/test_math_functions.py, numba_dpex/tests/kernel_tests/test_print.py, numba_dpex/tests/kernel_tests/test_scalar_arg_types.py, numba_dpex/tests/kernel_tests/test_usm_ndarray_args.py
The PR adds versions of existing kernel unit tests to the `numba_dpex.experimental.kernel`. The work is a prerequisite to identify gaps before migrating features from `numba_dpex.experimental` to the top-level `numba-dpex` module.
Matrix of existing kernel unit tests
| Test name  | Status | Notes|
| ------------- | ------------- |------|
| `test_atomic_op`  | *Not applicable* | Superseded by new `AtomicRef` tests in experimental module.|
| `test_barrier`  | **_TODO_** | Experimental needs a test for `group_barrier` with work-group scope.|
| `test_caching`  | *Not applicable* |The feature is redundant as experimental module uses Numba's function overload caching.|
| `test_complex_array` | **Done** |Renamed to `test_complex_array_kernel_arg` |
| `test_dpnp_ndarray_args` | **Done** | |
| …
=> Tests/port existing kernel tests to experimental 

.github/workflows/conda-package.yml
oneAPI 2024.1 is now publicly available. The GDB tests are failing in Github CI because the workflow is pulling in 2024.1 basekit but 2024.0 gdb. The PR fixes the url to now use gdb 2024.1.
=> Update oneapi gdb* to 2024.1

docs/source/conf.py, docs/source/sycl_spec_links.py, numba_dpex/kernel_api/atomic_fence.py, numba_dpex/kernel_api/atomic_ref.py, numba_dpex/kernel_api/barrier.py, numba_dpex/kernel_api/index_space_ids.py, numba_dpex/kernel_api/launcher.py, numba_dpex/kernel_api/local_accessor.py, numba_dpex/kernel_api/memory_enums.py, numba_dpex/kernel_api/private_array.py, numba_dpex/kernel_api/ranges.py
- Makes sure that summary fits on one line.
- Add links to sycl specs
- Adds some missing Args and Return tags to docstring.
=> Improve docstring for kernel_api functions.

numba_dpex/core/descriptor.py, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/parfors/kernel_templates/range_kernel_template.py
The range kernel template is used by the parfor kenrel builder to generate a range kernel from a parfor node. The PR migrates the template to the new kernel API.
=> Port the parfor range kernel template to new API.

docs/source/index.rst, docs/source/supported_sycl_features.rst, docs/source/user_guide/kernel_programming/index.rst
Adds a page on the documentation site listing SYCL kernel programming features supported in numba-dpex.
=> [Documentation] Add a comparison between SYCL and numba-dpex.

numba_dpex/core/parfors/kernel_templates/reduction_template.py
There is a minor left over issue in the reduction_template that prevents removal of `ocl` module. The PR replaces uses of `dpex.barrier` with `kernel_api.group_barrier`.
=> Update reduction_template to use kapi.group_barrier

numba_dpex/tests/dpjit_tests/dpnp/test_target_specific_overload.py
Update unit test so that it works in `new_style` Numba error capture mode.
=> Fix test case to work with NUMBA_CAPTURED_ERRORS=new_style

CHANGELOG.md
Changelog updates for upcoming 0.23
=> Changelog for 0.23

numba_dpex/examples/kernel/matmul.py
The `matmul` examples fails in CI as dpctl was updated to a new API. The PR fixes the example by using latest dpctl API.
=> Update example to use latest dpctl API.

conda-recipe/bld.bat
This PR fixes the windows wheel copying by returning it to the previous cmd. We don't need to store anything in the artifacts except the wheel package. Also, for some reason, cmd does not work correctly and does not save anything in the artifacts at all and the wheel package is missing
=> fix windows wheels copy cmd

numba_dpex/core/typing/dpnpdecl.py, numba_dpex/dpnp_iface/dpnp_ufunc_db.py
Fix for dpnp ufunc db creation caused by addition of nin, nout and types to dpnp math functions in latest version of dpnp.
=> Fix for dpex failure caused by addition of nin, nout and types

conda-recipe/meta.yaml, pyproject.toml
Pin spirv version due to driver runtime bug on windows with the kernel binary produced by llvm-spirv>2024.1.
```
conda search local::numba-dpex==0.23* --info
Loading channels: done
numba-dpex 0.23.0rc1 py310h2e52968_8
------------------------------------
file name   : numba-dpex-0.23.0rc1-py310h2e52968_8.tar.bz2
name        : numba-dpex
version     : 0.23.0rc1
build       : py310h2e52968_8
build number: 8
size        : 463 KB
license     : Apache-2.0
subdir      : win-64
url         : file:///C:/Users/yevhenii/scoop/apps/miniconda3/current/conda-bld/win-64/numba-dpex-0.23.0rc1-py310h2e52968_8.tar.bz2
md5         : 25c1eb70be9e3b3ea5527206ca69fc71
timestamp   : 2024-04-22 16:53:12 UTC
dependencies:
- dpcpp-cpp-rt >=2024.1,<2025.0a0
- dpcpp-cpp-rt >=2024.1.0,<2025.0a0
- dpcpp-llvm-spirv …
```
=> Pin dpcpp-llvm-spirv version

conda-recipe/meta.yaml, pyproject.toml
Since `dpcpp-llvm-spirv` relase for python 3.11 in `dppy/label/dev` we can remove exception for it in package meta
=> Remove dpcpp 2023 restriction workaround

numba_dpex/core/descriptor.py, numba_dpex/core/parfors/kernel_builder.py, numba_dpex/core/parfors/kernel_templates/kernel_template_iface.py, numba_dpex/core/parfors/kernel_templates/range_kernel_template.py, numba_dpex/core/parfors/kernel_templates/reduction_template.py, numba_dpex/core/parfors/parfor_lowerer.py, numba_dpex/core/parfors/parfor_pass.py, numba_dpex/core/parfors/parfor_sentinel_replace_pass.py, numba_dpex/core/parfors/reduction_helper.py, numba_dpex/core/parfors/reduction_kernel_builder.py, numba_dpex/core/pipelines/kernel_compiler.py, numba_dpex/core/types/dpnp_ndarray_type.py, numba_dpex/kernel_api_impl/spirv/dispatcher.py
What was done:
- Compile parfor kernels using `SpirvDispatcher`.
- Add internal option to compile kernel with Prange support. This mode inserts prange body instead of `__seninel__ = 0`. Ideally it  must be replace to some internal dedicated function call like `numba_dpex.core.insert_parfor_body()`.
- Remove kernel allocation aside of dpjit compilation. Now parfor kernel specific SPIRV is a part of dpjit function inserted as a string constant. It unblocks dpjit function caching on disk
Checklist:
=> Migrate parfor to SPIRVKernelDispatcher

.github/workflows/coverage.yml
Add source directory, so the generated xml file has the same root directory as a package repo.
Closes #1439
=> Fix coveralls sources

conda-recipe/bld.bat, conda-recipe/build.sh, conda-recipe/meta.yaml, pyproject.toml
Load build requirements from pyproject during conda build.
=> Improve pyproject.toml

MANIFEST.in, conda-recipe/bld.bat, conda-recipe/build.sh, setup.py
Reverts #1447 and fixes root cause of the problem: Manifest was setup incorrectly, that resulted wheel to install some artifacts in the root directory. It is no longer required as it managed through the setuptools configuration directly.
=> Remove MANIFEST.in

numba_dpex/kernel_api_impl/spirv/spirv_generator.py, numba_dpex/tests/codegen/test_intenum_literal_codegen.py, numba_dpex/tests/debugging/gdb.py, numba_dpex/tests/debugging/test_breakpoints.py, numba_dpex/tests/debugging/test_info.py, numba_dpex/tests/debugging/test_stepping.py
- The PR introduces changes to the gdb-oneapi unit tests to support running the tests on Intel Max GPU.
- Updated the `test_intenum_literal_codegen.py` test case to handle a corner case that was identified during testing on Intel Max GPU.
- Loads the `SPV_INTEL_variable_length_array` SPIR-V extension for llvm-spirv translation as it is required for supporting private arrays on Intel Max GPU.
=> Required fixes to run test suite on Max GPU

conda-recipe/build.sh, conda-recipe/meta.yaml
This PR is designed to fix the problem described here: [SAT-6873](https://jira.devtools.intel.com/browse/SAT-6873). I did some experiments and found out that using pep600 wheel tag prevents the wheel from being installed on non-supported platforms
=> update wheel tag with pep600

numba_dpex/core/runtime/_dpexrt_python.c
Ref-count of `arrayobj` was not decremented after use in case `dpnp.ndarray` object was being processed.
Change the flow of managing lifetime of Python temporaries in unboxing code.
This PR replaces use of `obj` in NRT structure with use of `arrayobj`, and shifts ref-count manipulation of `obj` into `PyUSMNdArray_ARRAYOBJ`.
=> Fixed ref-counting of Python object temporaries in unboxing code

numba_dpex/core/runtime/_dpexrt_python.c, numba_dpex/core/runtime/context.py
Replace `NRT_MemInfo` allocation from std's `malloc` to NRT API, so they handle the same way for the whole lifetime. Was causing crashes under expect tests
=> Use nrt api to allocate meminfo object

.github/workflows/conda-package.yml, pyproject.toml
Make CI green, so we can merge dependabot PRs
=> Pin numba to 0.59 and use windows-2019 for build

conda-recipe/meta.yaml, pyproject.toml
The issue was with IGC driver on windows. It was tested that nightly builds of drivers are passing tests.
DO NOT MERGE until allowance from INFRA team.
=> Remove SPIRV version restriction

CHANGELOG.md
Updated CHANGELOG with latest changes since 4da339d
=> Updated Changelog with all changes going into 0.23

environment/docs.yml
Pin `sphinx-autoapi==3.0.0`. Newer version shrinks multiple files into one that breaks doc generation.
=> Pin sphinx-autoapi==3.0.0

.github/workflows/conda-package.yml, README.md, conda-recipe/meta.yaml, docs/source/getting_started.rst, environment/coverage.yml, environment/docs.yml, environment/pre-commit.yml
Changes existing github workflows based on https://github.com/IntelPython/numba-dpex/issues/1480#issuecomment-2230025965
Fixes #1481
=> Switch workflows to not use intel channel.
