- README.md
> Fix run test command

- conda-recipe/meta.yaml
- numba_dppy/compiler.py
- setup.py
> Update to new API of dpCtl 0.4.0 related to USM

- numba_dppy/tests/test_controllable_fallback.py
Change test case from DPPYTestCase to unittest.TestCase
> Fix fallback test

- DEBUGGING.md
> Extended docs for debugger

- numba_dppy/dpctl_functions.py
- numba_dppy/dpnp_glue/dpnp_linalgimpl.py
- numba_dppy/dpnp_glue/dpnp_sort_search_countimpl.py
- numba_dppy/dpnp_glue/dpnp_statisticsimpl.py
- numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
- numba_dppy/dpnp_glue/dpnpimpl.py
- numba_dppy/tests/test_dpnp_functions.py
This PR refactors code to reduce redundancy and improves reuse.
> Cleanup redundant code

- docs/dppy/device-functions.rst
- numba_dppy/examples/dppy_func.py
> Docs for Device Functions

- docs/dppy/index.rst
- docs/dppy/reduction.rst
- numba_dppy/examples/sum_reduction.py
- numba_dppy/examples/sum_reduction_ocl.py
- numba_dppy/examples/sum_reduction_recursive_ocl.py
> Docs for GPU Reduction

- conda-recipe/bld.bat
- conda-recipe/build.sh
- conda-recipe/meta.yaml
- Add wheels build
- Use manylinux1 for Python 3.6
- Use manylinux2014 for Python > 3.6
> Add wheels build + Update linux build tag for wheels

- CHANGELOG.md
- README.md
- conda-recipe/meta.yaml
- numba_dppy/__init__.py
- numba_dppy/compiler.py
- numba_dppy/dppy_passes.py
- numba_dppy/examples/sum_reduction_ocl.py
- numba_dppy/examples/sum_reduction_recursive_ocl.py
- numba_dppy/ocl/ocldecl.py
- numba_dppy/ocl/oclimpl.py
- numba_dppy/ocl/stubs.py
- numba_dppy/tests/test_atomic_op.py
- numba_dppy/tests/test_barrier.py
This PR should be merged after PR https://github.com/IntelPython/numba/pull/175.
> Changes required for updating to Numba 0.52.0

- numba_dppy/tests/test_dpnp_functions.py
- Fix test_uniform for #242 
- Fix assertion
> Fix rng tests

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- docs/CONTRIBUTING.md
Similar to https://github.com/IntelPython/dpctl/pull/282
> Add Bandit

- numba_dppy/dppy_lowerer.py
- numba_dppy/tests/test_controllable_fallback.py
- numba_dppy/tests/test_dppy_fallback.py
- numba_dppy/tests/test_parfor_lower_message.py
- numba_dppy/tests/test_with_context.py
Use SYCL device instead of DPPY device.
> Improve message printed during parfor lowering.

- numba_dppy/dpnp_glue/dpnp_transcendentalsimpl.py
> Initial port of sum

- numba_dppy/tests/conftest.py
- numba_dppy/tests/test_debug.py
This PR updates the filter string in `conftest.py`
> Update SYCL Filter String

- numba_dppy/dppy_lowerer.py
Moving some docstring changes out of the kernel wrapper PR to reduce diff.
> Fix comments and convert to docstring.

- numba_dppy/tests/kernel_tests/test_atomic_op.py
This PR extends the native atomic ops on local addrspace variables.
> Added local addrspace testing for native atomic op

- numba_dppy/examples/debug/commands/function_breakpoint
- numba_dppy/examples/debug/commands/local_variables
- numba_dppy/examples/debug/commands/stepping
- scripts/run_debug_examples.sh
> Add scripts for testing debug examples

- docs/user_guides/debugging/debugging_environment.rst
- docs/user_guides/debugging/features.rst
- docs/user_guides/debugging/index.rst
- docs/user_guides/debugging/local_variables.rst
- docs/user_guides/debugging/set_up_machine.rst
- docs/user_guides/debugging/stepping.rst
- docs/user_guides/kernel_programming_guide/random.rst
- numba_dppy/examples/debug/commands/simple_sum
- numba_dppy/examples/debug/simple_sum.py
Text moved to https://github.com/IntelPython/numba-dppy/issues/453.
This is only PR with part of fixes for #453.
> Improving User Guide section on Debugging with GDB

- scripts/diag_env.sh
This script helped me configure Ubuntu 20.04 for debugging.
I think it is useful for all any diagnostic. Also it could be moved to dpctl.
> Add scripts/diag_env.sh

- docs/user_guides/debugging/debugging_environment.rst
- docs/user_guides/debugging/index.rst
- numba_dppy/examples/debug/commands/simple_sum
- numba_dppy/examples/debug/simple_dppy_func.py
- numba_dppy/examples/debug/simple_sum.py
> Fix examples

- docs/user_guides/debugging/stepping.rst
- numba_dppy/examples/debug/commands/function_breakpoint
- numba_dppy/examples/debug/commands/local_variables
- numba_dppy/examples/debug/commands/next
- numba_dppy/examples/debug/commands/sheduler_locking
- numba_dppy/examples/debug/commands/simple_sum
- numba_dppy/examples/debug/commands/stepi
- numba_dppy/examples/debug/commands/stepping
- scripts/run_debug_examples.sh
Documentation about commands step/stepi/next
> Docs step/stepi/next

- docs/user_guides/debugging/limitations.rst
- docs/user_guides/debugging/local_variables.rst
- numba_dppy/examples/debug/commands/local_variables
Update docs about debugger local vars
> Update docs about debugger local vars

- docs/user_guides/debugging/debugging_environment.rst
- docs/user_guides/debugging/index.rst
- numba_dppy/examples/debug/dppy_func.py
- numba_dppy/examples/debug/simple_dppy_func.py
- numba_dppy/examples/debug/simple_sum.py
- numba_dppy/examples/debug/sum.py
> Fix NUMBA_OPT and debug flag

- docs/user_guides/debugging/backtrace.rst
- docs/user_guides/debugging/features.rst
- numba_dppy/examples/debug/commands/backtrace
- scripts/run_debug_examples.sh
> Add docs about backtrace

- docs/user_guides/debugging/index.rst
- docs/user_guides/debugging/tools.rst
- numba_dppy/examples/debug/njit_basic.py
> Add docs for get dwarf

- numba_dppy/dppy_parfor_diagnostics.py
Fix flake in ParforDiagnostics
Closes https://github.com/IntelPython/numba-dppy/issues/312.
Fixes #461.
> Fix undefined variables in ParforDiagnostics

- docs/user_guides/debugging/info.rst
- numba_dppy/examples/debug/commands/docs/info_func
- numba_dppy/examples/debug/commands/info_func
- scripts/run_debug_examples.sh
This PR updates the documentation examples in the `Information` section and adds commands for `info functions`
> Update docs for info functions

- docs/user_guides/debugging/backtrace.rst
- docs/user_guides/debugging/breakpoints.rst
- numba_dppy/examples/debug/commands/backtrace_kernel
- numba_dppy/examples/debug/commands/docs/backtrace_kernel
- numba_dppy/examples/debug/commands/docs/break_func
- numba_dppy/examples/debug/commands/docs/break_line_number
- numba_dppy/examples/debug/commands/docs/break_nested_func
- scripts/run_debug_examples.sh
Update docs about breakpoints and backtrace
> Update docs about breakpoints and backtrace

- docs/user_guides/debugging/breakpoints.rst
- numba_dppy/examples/debug/commands/break_conditional
- numba_dppy/examples/debug/commands/docs/break_conditional
Fixes https://github.com/IntelPython/numba-dppy/issues/327.
Fixes small title issues.
> Docs for `break ... if cond`

- docs/user_guides/debugging/backtrace.rst
- docs/user_guides/debugging/common_issues.rst
- docs/user_guides/debugging/debugging_environment.rst
- docs/user_guides/debugging/features.rst
- docs/user_guides/debugging/index.rst
- docs/user_guides/debugging/local_variables.rst
- docs/user_guides/debugging/stepping.rst
Common issues and tips for resolving have been moved to a separate section
> Moved common issues to a separate file

- docs/user_guides/debugging/index.rst
- docs/user_guides/debugging/info.rst
1. Removed "debugger" in "GDB debugger".
2. Changed style of "Regex" to bold instead italic.
> Refactor GDB docs

- CHANGELOG.md
> update CHANGELOG 0.14.4

- README.md
- conda-recipe/meta.yaml
- docs/user_guides/getting_started.rst
- setup.py
> Add `packaging` in run dependencies

- numba_dppy/tests/integration/test_dpnp_interop.py
- numba_dppy/tests/integration/test_usm_ndarray_interop.py
- numba_dppy/tests/test_array_utils.py
- numba_dppy/tests/test_strided_array.py
> Skip tests for run without GPU

- .github/workflows/conda-package.yml
Add integration testing with packages from `-c dppy/label/dev`.
Also this PR:
> Add integration channels

- README.md
> Update test matrix in README

- .coveragerc
- environment.yml
- setup.cfg
Add configurations which allows collect coverage when running tests parallel.
> Add support pytest-cov and pytest-xdist

- .github/workflows/conda-package.yml
> Use Python 3.9 [public CI]

- CHANGELOG.md
- README.md
> Update CHANGLEOG and Readme.md

- conda-recipe/meta.yaml
- numba_dppy/tests/test_debug_dppy_numba.py
This PR adds and modifies GDB tests for new `Numba` debugging features. PR for the [SAT-4286].
> Change GDB tests for new Numba features

- setup.py
> Update clang to icx

- CHANGELOG.md
- conda-recipe/bld.bat
- conda-recipe/build.sh
- setup.py
> Merge release0.17 to main

- .github/workflows/conda-package.yml
- CHANGELOG.md
Fix the problem due to which the upload was launched for pull requests
> Fix upload conditions for main and release branches [Public CI]

- numba_dppy/tests/_helper.py
- numba_dppy/tests/passes/test_rename_numpy_function_pass.py
- numba_dppy/tests/test_black_scholes.py
- numba_dppy/tests/test_controllable_fallback.py
- numba_dppy/tests/test_device_array_args.py
- numba_dppy/tests/test_dpnp_functions.py
- numba_dppy/tests/test_dppy_fallback.py
- numba_dppy/tests/test_dppy_func.py
- numba_dppy/tests/test_offload_diagnostics.py
- numba_dppy/tests/test_parfor_lower_message.py
- numba_dppy/tests/test_prange.py
- numba_dppy/tests/test_sum_reduction.py
- numba_dppy/tests/test_usmarray.py
- numba_dppy/tests/test_with_context.py
Convert all unittests to pytests
> Convert unittest to pytest

- numba_dppy/__init__.py
- numba_dppy/tests/_helper.py
- numba_dppy/tests/test_black_scholes.py
- numba_dppy/tests/test_controllable_fallback.py
- numba_dppy/tests/test_device_array_args.py
- numba_dppy/tests/test_dpnp_functions.py
- numba_dppy/tests/test_dppy_fallback.py
- numba_dppy/tests/test_dppy_func.py
- numba_dppy/tests/test_offload_diagnostics.py
- numba_dppy/tests/test_parfor_lower_message.py
- numba_dppy/tests/test_prange.py
- numba_dppy/tests/test_sum_reduction.py
- numba_dppy/tests/test_with_context.py
Proposal to change functions 'has_gpu_queues' and 'has_cpu_queues' to three new: has_opencl_gpu, has_opencl_cpu, has_level_zero
> Redesign helper functions

- .github/workflows/conda-package.yml
- CHANGELOG.md
- conda-recipe/meta.yaml
- conda-recipe/run_test.sh
- numba_dppy/tests/kernel_tests/test_atomic_op.py
> Release 0.17.4

- .github/workflows/conda-package.yml
- .github/workflows/generate-coverage.yml
- environment.yml
This change is for showing dpnp import problem when installed from dppy/label/dev.
> Add check for DPNP and pin MKL version

- .github/CODEOWNERS
Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Add CODEOWNERS for distributing review process

- MANIFEST.in
- numba_dppy/tests/test_examples.py
- setup.py
It allows use examples in tests (i.e. debugging tests).
> Add examples into package

- .github/workflows/conda-package.yml
> Run public CI on pull request

- numba_dppy/tests/debugging/common.py
- numba_dppy/tests/debugging/test_breakpoints.py
- numba_dppy/tests/njit_tests/dpnp/test_numpy_logic.py
> Fix codestyle black

- .github/workflows/generate-docs.yml
Fix documentation generation pipeline
> Fix documentation generation

- .github/actions/setup-numba-dppy/action.yml
- .github/workflows/coverage.yml
- .github/workflows/generate-coverage.yml
- .github/workflows/gh-pages.yml
- .github/workflows/license.yml
- environment/coverage.yml
> Add `setup-numba-dppy` action

- .github/actions/setup-anaconda-client/action.yml
- .github/actions/setup-conda-build/action.yml
- .github/workflows/conda-package.yml
- .github/workflows/coverage.yml
- .github/workflows/gh-pages.yml
- scripts/build_conda_package.sh
> Fixes for public CI

- .github/workflows/conda-package.yml
Tries to fix the failure in uploading packages for Linux to `dppy/label/dev'
> Try fixing the package uploading for Linux

- .github/actions/setup-anaconda-client/action.yml
- .github/workflows/conda-package.yml
Fixes the Linux package upload to anaconda cloud.
> Triage the failing upload to anaconda cloud for Linux

- .github/CODEOWNERS
- .github/pull_request_template.md
Added the template, also added @diptorupd to `CODEOWNERS` file.
> Add pull request template

- .github/CODEOWNERS
- .github/workflows/conda-package.yml
- conda-recipe/meta.yaml
- docs/user_guides/getting_started.rst
- environment.yml
- environment/coverage.yml
- environment/docs.yml
- numba_dpex/dpnp_iface/dpnp_array_ops_impl.py
- numba_dpex/dpnp_iface/dpnp_fptr_interface.pyx
- numba_dpex/tests/njit_tests/dpnp/test_numpy_array_ops.py
Modified `conda-recipe/meta.yaml` to remove excessive pinning.
> Remove excessive pinning

- .pre-commit-config.yaml
Added a pre-commit hook for black.
> Run black in precommit

- README.md
- test.py
Adds the pre-commit badge to our README.
> Add a precommit badge, because why not

- .pre-commit-config.yaml
- docs/CoreFeatures.rst
- docs/developer_guides/dpnp_integration.rst
- docs/index.rst
Adds a precommit hook for blacken-docs to check source snippets in doc files. Fixes issues identified by blacken-docs.
> Adds a pre-commit hook for blackend docs

- .github/workflows/coverage.yml
- .github/workflows/gh-pages.yml
- environment.yml
- environment/coverage.yml
- environment/docs.yml
- Addressing issue #811 
- Yes
- Yes
- Yes
- Yes
> Bumping dpnp to 0.10.2 for public CI

- CHANGELOG.md
1. Updated change log for fix made in 0.19.0.
2. Updated change log for 0.18.1.
> Updated change log for 0.19.0 release.

- .github/workflows/black.yml
- .github/workflows/conda-package.yml
- .github/workflows/numba.yml
- .github/workflows/pre-commit.yml
To avoid GLibc issue with the latest Ubuntu, the conda package will be build use 20.04.
> Switched from Ubuntu-latest to Ubuntu-20.04 for conda package build.

- numba_dpex/ocl/stubs.py
- [Y] Have you provided a meaningful PR description?
- [N] Have you added a test, reproducer or referred to an issue with a reproducer?
- [Y] Have you tested your changes locally for CPU and GPU devices? Tested numba-dpex build + visually inspected documentation
- [Y] Have you made sure that new changes do not introduce compiler warnings?
- [N] If this PR is a work in progress, are you filing the PR as a draft?
> Atomic functions description

- numba_dpex/examples/usm_ndarray.py
Fixes #839 
The PR updates the `usm_ndarray.py` to properly create `dpctl.tensor.usm_ndarray` arrays and pass them to a kernel instead of copying NumPy arrays to `dpctl.tensor.usm_ndarray`.
> Update the usm_ndarray example.

- .gitignore
- .vscode/extensions.json
Add vscode settings files to gitignore
> Update gitignore to ignore vscode settings files.

- numba_dpex/tests/dpjit_tests/dpnp/test_dpnp_empty.py
Adds few extra checks to dpnp.empty unit tests.
> Improve dpnp.empty unit tests.

- README.md
Adds a README badge to our gitter.im chatroom
> Add a badge to our gitter chatroom

- numba_dpex/tests/kernel_tests/test_caching.py
This added unit-test preform different permutative caching operations and checks the validity of state of the cache.
> Adding a rigorous test for caching

- docs/conf.py
- environment/docs.yml
- [Y] Have you provided a meaningful PR description?
- [N] Have you added a test, reproducer or referred to an issue with a reproducer?
- [N] Have you tested your changes locally for CPU and GPU devices?
- [N] Have you made sure that new changes do not introduce compiler warnings?
- [N] If this PR is a work in progress, are you filing the PR as a draft?
> Enable Google Analytics

- CHANGELOG.md
> Update/changelog 0.20

- CHANGELOG.md
> Release 0.20

- numba_dpex/dpnp_iface/arrayobj.py
> Fixed layout in dpnp overload.

- numba_dpex/dpnp_iface/_intrinsic.py
**Some fixes:**  
- `fill_arrayobj()` takes `sig`, `args` and also `fill_value`, this duplication is not needed, since the value is supposed to be in `args` already.
- In the `fill_arrayobj()`, we check if the `fill_value` is `float` by probing `args[1]`. But when there is no `fill_value` in `args`, we are testing on a wrong argument, this happens in the case of `dpnp.ones()`, `dpnp.zeros()` etc. which is not correct. *But it doesn't produce any bug or incorrect result, since the `fill_value` is either `0` or `1`.*
- Now the `codegen()` functions in all intrinsics are cleaner and streamlined.
> Fix fill_arrayobj

- .github/CODEOWNERS
> Better partition code ownership.

- numba_dpex/tests/core/passes/__init__.py
- numba_dpex/tests/core/runtime/__init__.py
- numba_dpex/tests/core/types/DpctlSyclQueue/__init__.py
- numba_dpex/tests/core/types/DpnpNdArray/__init__.py
- numba_dpex/tests/core/types/USMNdAArray/__init__.py
- numba_dpex/tests/dpjit_tests/dpnp/__init__.py
- numba_dpex/tests/dpjit_tests/parfors/__init__.py
- numba_dpex/tests/misc/__init__.py
> Added __init__.py to fix missing tests on CI.

- .github/workflows/conda-package.yml
- .github/workflows/coverage.yml
Adding some workflow sections to dump conda environments on CI. These can be very useful in debugging CI runs.
> Adding workflow sections to dump conda environments on CI

- docs/index.rst
This PR resolves a broken hyperlink issue in the documentation. The hyperlink should direct users to the CONTRIBUTING file, but currently, it is not functioning correctly. To fix this, the PR modifies the hyperlink to correctly point to the `CONTRIBUTING.md` file.
> docs: update the link to the CONTRIBUTING.md file

- Dockerfile
- conda-recipe/meta.yaml
- docs/user_guides/getting_started.rst
- environment.yml
- environment/coverage.yml
- environment/docs.yml
- setup.py
We no longer have any cython components in numba-dpex and as such the dependency on cython is removed from setup and conda-recipe.
> Cython is no longer a dependency to build numba-dpex.

- .github/actions/setup-numba-dpex/action.yml
- environment/docs.yml
Fixes the failing Gh-pages workflow
> Fix docs workflow.

- CHANGELOG.md
> Updated changelog for release 0.21

- numba_dpex/core/kernel_interface/indexers.py
The PR contains a typo fixes in error messages of the kernel interface. Instead of `Unknwon` it should be `Unknown`.
> fix: typo in error messages of kernel interface

- numba_dpex/examples/sum_reduction.py
Just make it work with any size of array
> Remove ^2 restriction on sum example

- docs/sources/user_manual/kernel_programming/writing_kernels.rst
WIP on revised and improved documentation.
> WIP on revised and improved documentation

- CHANGELOG.md
Add all changes from closed PRs since last release
n/a
n/a
> Add 0.21.1 changelog

- docs/source/getting_started.rst
Improved the instructions to build `numba-dpex` from source using setuptools and other minor edits.
> Improvements to getting_started guide.

- README.md
> Fix broken Getting Started link in README

- CHANGELOG.md
> Updated CHANGELOG for 0.21.2

- SECURITY.md
Adds an Intel standard security policy. 
Fixes #575
> Adds a security policy

- .github/workflows/conda-package.yml
> Add python 3.11 support

- CHANGELOG.md
The CHNAGELOG changes for the upcoming 0.21.3 minor release.
> Changelog updates for 0.21.3

- .gitignore
Adds the `_skbuild` directory to .gitignore
> Ignore the _skbuild directory.

- CHANGELOG.md
> Update changelog for release 0.21.3

- numba_dpex/tests/core/types/DpctlSyclEvent/test_models.py
Previous PR was merged before tests passed. We need to add this restriction as a merge blocker.
> Fix sycl event tests

- numba_dpex/core/passes/dufunc_inliner.py
- numba_dpex/core/passes/passes.py
- numba_dpex/core/types/dpnp_ndarray_type.py
Removed dead code regions identified by Coverity.
> Remove dead code to silence coverity errors.

- numba_dpex/core/passes/dufunc_inliner.py
- numba_dpex/core/passes/passes.py
- numba_dpex/core/types/dpnp_ndarray_type.py
Removed dead code regions identified by Coverity.
> [gold/2021] Remove dead code to silence coverity errors.

- numba_dpex/core/codegen.py
Fixes a minor typo in a docstring
> Fix typo in docstring

- CHANGELOG.md
Update changelog for release 0.21.4
> Update changelog for release 0.21.4

- .github/workflows/license.yml
Updates the `addlicense` workflow that was failing for the last few days.
> Fixes the failing addlicense workflow.

- numba_dpex/core/codegen.py
- numba_dpex/experimental/decorators.py
- numba_dpex/experimental/kernel_dispatcher.py
Addresses the leftover issues in the `experimetal` module identified by `pylint`. 
Fixes #1196
> Fix Pylint issues in the numba_dpex.experimental module.

- .github/workflows/gh-pages.yml
Change compiler to sycl for github pages generation.
> Fix github pages build

- numba_dpex/core/codegen.py
- numba_dpex/core/kernel_interface/spirv_kernel.py
- numba_dpex/tests/experimental/test_compiler_warnings.py
- numba_dpex/tests/experimental/test_inline_threshold_config.py
- numba_dpex/tests/misc/test_warnings.py
- Removes duplicate code inside codegen module.
- Adds a unit test to make sure a compiler warning is generated
when the `inline_threshold` is set to >=3
> Removes code duplication and adds new unit tests.

- numba_dpex/experimental/launcher.py
> Fix typos in docstring

- README.md
- setup.py
This PR is designed to fix metadata in wheels. `License :: OSI Approved :: Apache 2.0` is actually incorrect definition for a license in wheels, because of this, when uploading a package to pypi, we have to repackage wheel by changing the license to the correct one. Also, there are no instructions in README for installing wheels and conda packages
> Update license and readme to fix wheels metadata

- numba_dpex/__init__.py
- numba_dpex/core/caching.py
- numba_dpex/core/codegen.py
- numba_dpex/core/compiler.py
- numba_dpex/core/config.py
- numba_dpex/core/descriptor.py
- numba_dpex/core/kernel_interface/dispatcher.py
- numba_dpex/core/kernel_interface/func.py
- numba_dpex/core/kernel_interface/spirv_kernel.py
- numba_dpex/core/parfors/kernel_builder.py
- numba_dpex/core/parfors/parfor_lowerer.py
- numba_dpex/core/passes/passes.py
- numba_dpex/core/pipelines/kernel_compiler.py
- numba_dpex/core/types/usm_ndarray_type.py
- numba_dpex/core/typing/typeof.py
- numba_dpex/core/utils/kernel_launcher.py
- numba_dpex/decorators.py
- numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py
- numba_dpex/experimental/kernel_dispatcher.py
- numba_dpex/experimental/literal_intenum_type.py
- numba_dpex/experimental/target.py
- numba_dpex/experimental/typeof.py
- numba_dpex/ocl/oclimpl.py
- numba_dpex/spirv_generator.py
- numba_dpex/tests/__init__.py
- numba_dpex/tests/_helper.py
- numba_dpex/tests/debugging/gdb.py
- numba_dpex/tests/kernel_tests/test_dump_kernel_llvm.py
- numba_dpex/tests/misc/test_warnings.py
- numba_dpex/utils/array_utils.py
Move `config.py` into `numba_dpex/core`.
And fix associated circular imports.
> Refactor config.py (for docs)

- numba_dpex/core/runtime/_dpexrt_python.c
Updates the `FIXME` comment in `_dpexrt_python.c`. The comment was incorrect as the logic to compute strides from dpctl/dpnp actually works for all layouts and the `experimental` kernel now can support `F` and strided layouts.
> Update FIXME comment in stride computation.

- .github/workflows/conda-package.yml
Execute `tests` and `examples` in parallel with should result in approx 10 min WF speed up.
> Run tests and examples in parallel

- .github/workflows/openssf-scorecard.yml
- README.md
Adds OpenSSF scorecard workflow to numba-dpex.
> Adds OpenSSF scorecard

- README.md
> Try once more to fix up OpenSSF badge

- numba_dpex/experimental/_kernel_dpcpp_spirv_overloads/_atomic_ref_overloads.py
This PR adds "convergent" and "nounwind" attributes to atomic fetch_phi function declarations and callsites. 
It also adds the same attributes to load, store, exchange and compare_exchange atomic function callsites. Adding the same attributes to these functions declarations was part of PR #1336 .
These attributes are required as per the ir generated by dpc++ code.
> Adding "convergent" and "nounwind" attributes to atomic operations

- numba_dpex/kernel_api_impl/spirv/target.py
> Update docstring to avoid mysterious tm issue

- CHANGELOG.md
Updated changelog entry for upcoming 0.22 release
> Changelog updates for 0.22 release

- numba_dpex/tests/experimental/codegen/test_inline_threshold_codegen.py
- numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_fetch_phi.py
- numba_dpex/tests/experimental/kernel_api_overloads/spv_overloads/test_atomic_ref.py
- numba_dpex/tests/experimental/test_async_kernel.py
- numba_dpex/tests/experimental/test_compiler_warnings.py
- numba_dpex/tests/experimental/test_inline_threshold_config.py
- numba_dpex/tests/experimental/test_kernel_specialization.py
- numba_dpex/tests/experimental/test_strided_dpnp_array_in_kernel.py
- numba_dpex/tests/experimental/test_supported_array_types_as_kernel_args.py
- numba_dpex/tests/experimental/test_target_specific_overload.py
Use new style of get indexes in experimental kernel
> Use item object for experimental kernels in tests

- .pre-commit-config.yaml
- numba_dpex/core/utils/kernel_flattened_args_builder.py
- numba_dpex/core/utils/kernel_launch_arg_builder.py
- numba_dpex/core/utils/kernel_launcher.py
- Splits out the logic to build kernel launch arguments to a separate module.
- Simplifies the logic to keep track of the argument position.
No new feature was introduced and only code was refactored.
> Refactor kernel_launcher module.

- .github/workflows/coverage.yml
Use official github actions for coveralls
> Use official github actions for coveralls

- numba_dpex/examples/debug/sum_local_vars.py
- numba_dpex/examples/kernel/pipelining.py
- numba_dpex/examples/kernel/sum_reduction_recursive.py
Initial conversion of examples to new kernel API missed few files. The PR addresses the remaining changes to port every example to use the new kernel API.
> Updates few leftover examples to use new kernel api

- README.md
This PR just fixes a small inaccuracy in the name: [SAT-6766](https://jira.devtools.intel.com/browse/SAT-6766)
> Set correct package name in README.md
